'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

export type Language = 'es' | 'en'

const TRANSLATIONS = {
  es: {
    locale: 'es-ES',
    nav: {
      dashboard: 'Dashboard',
      calendar: 'Calendario',
      services: 'Servicios',
      clients: 'Clientes',
      settings: 'Configuracion',
    },
    // Root-level keys used by settings (backward compat)
    saveChanges: 'Guardar cambios',
    signOut: 'Cerrar sesion',
    changesSaved: 'Cambios guardados',
    saveError: 'Error al guardar',
    welcome: 'Bienvenido',
    upgradePlan: 'Actualizar',
    language: { label: 'Idioma', es: 'Espanol', en: 'English' },

    dashboard: {
      title: 'Dashboard',
      subtitle: 'Gestiona tus reservas y citas',
      viewCalendar: 'Ver Calendario',
      reservationsToday: 'Reservas Hoy',
      appointmentsSubtitle: 'Citas programadas para hoy',
      businessCard: 'Negocio',
      notConfigured: 'Sin configurar',
      planCard: 'Plan',
      premium: 'Premium',
      free: 'Gratuito',
      allFeatures: 'Todas las funciones',
      basicAccess: 'Acceso básico',
      userCard: 'Usuario',
      activeAccount: 'Cuenta activa',
      newReservation: 'Nueva Reserva',
      createAppointment: 'Crea una nueva cita para tu cliente',
      goToCalendar: 'Ir al Calendario',
      clientsCard: 'Clientes',
      manageClients: 'Gestiona tu lista de clientes',
      viewClients: 'Ver Clientes',
      servicesCard: 'Servicios',
      configureServices: 'Configura tus servicios',
      viewServices: 'Ver Servicios',
      freePlan: 'Plan Gratuito',
      reservationsWord: 'reservas hoy',
      upgrade: 'Actualizar',
    },

    calendar: {
      title: 'Calendario',
      subtitle: 'Gestiona tus reservas y citas',
      view: 'Vista',
      day: 'Día',
      week: 'Semana',
      month: 'Mes',
      newReservation: 'Nueva Reserva',
      newShort: 'Nueva',
      today: 'Hoy',
      noReservationsToday: 'No hay reservas para hoy',
      unknownClient: 'Cliente desconocido',
      unknownService: 'Servicio desconocido',
      setupRequired: 'Configura tu negocio primero',
      setupRequiredDesc: 'Necesitas configurar tu negocio antes de crear reservas',
    },

    clients: {
      title: 'Clientes',
      subtitle: 'Administra tu base de clientes',
      newClient: 'Nuevo Cliente',
      totalClients: 'Total Clientes',
      newThisMonth: 'Nuevos este mes',
      withActiveReservations: 'Con reservas activas',
      search: 'Buscar clientes...',
      clientCol: 'Cliente',
      contactCol: 'Contacto',
      reservationsCol: 'Reservas',
      sinceCol: 'Desde',
      notFound: 'No se encontraron clientes',
      editTitle: 'Editar Cliente',
      newTitle: 'Nuevo Cliente',
      editDesc: 'Modifica los datos del cliente',
      newDesc: 'Agrega un nuevo cliente a tu base de datos',
      fullName: 'Nombre completo',
      namePlaceholder: 'Nombre del cliente',
      emailLabel: 'Correo electronico',
      emailPlaceholder: 'cliente@email.com',
      phoneLabel: 'Telefono (opcional)',
      phonePlaceholder: '+51 999 999 999',
      notesLabel: 'Notas (opcional)',
      notesPlaceholder: 'Notas importantes sobre el cliente...',
      cancelBtn: 'Cancelar',
      createBtn: 'Crear cliente',
      saveBtn: 'Guardar cambios',
      detailTitle: 'Detalles del Cliente',
      editBtn: 'Editar',
      viewDetailsBtn: 'Ver detalles',
      deleteBtn: 'Eliminar',
      reservationHistory: 'Historial de Reservas',
      noReservations: 'Este cliente no tiene reservas',
      premiumRequired: 'El historial de reservas esta disponible en el plan Premium',
      upgradePremium: 'Actualizar a Premium',
      reservationsWord: 'reservas',
      confirmed: 'Confirmada',
      cancelled: 'Cancelada',
      rescheduled: 'Reprogramada',
      setupRequired: 'Configura tu negocio primero',
      setupRequiredDesc: 'Necesitas configurar tu negocio antes de agregar clientes',
    },

    services: {
      title: 'Servicios y Recursos',
      subtitle: 'Administra los servicios que ofreces y los recursos disponibles',
      servicesTab: 'Servicios',
      resourcesTab: 'Recursos',
      searchServices: 'Buscar servicios...',
      searchResources: 'Buscar recursos...',
      newService: 'Nuevo Servicio',
      newResource: 'Nuevo Recurso',
      serviceCol: 'Servicio',
      durationCol: 'Duracion',
      priceCol: 'Precio',
      statusCol: 'Estado',
      active: 'Activo',
      inactive: 'Inactivo',
      edit: 'Editar',
      delete: 'Eliminar',
      notFoundServices: 'No se encontraron servicios',
      notFoundResources: 'No se encontraron recursos',
      editServiceTitle: 'Editar Servicio',
      newServiceTitle: 'Nuevo Servicio',
      editServiceDesc: 'Modifica los datos del servicio',
      newServiceDesc: 'Agrega un nuevo servicio a tu catalogo',
      nameLabel: 'Nombre',
      namePlaceholder: 'Ej: Consulta General',
      descLabel: 'Descripcion',
      descPlaceholder: 'Descripcion del servicio...',
      durationLabel: 'Duracion (minutos)',
      priceLabel: 'Precio (opcional)',
      colorLabel: 'Color',
      serviceActive: 'Servicio activo',
      cancelBtn: 'Cancelar',
      createServiceBtn: 'Crear servicio',
      saveBtn: 'Guardar cambios',
      editResourceTitle: 'Editar Recurso',
      newResourceTitle: 'Nuevo Recurso',
      editResourceDesc: 'Modifica los datos del recurso',
      newResourceDesc: 'Agrega un nuevo recurso (sala, persona, equipo)',
      resourceNamePlaceholder: 'Ej: Consultorio 1',
      resourceDescPlaceholder: 'Descripcion del recurso...',
      resourceTypeLabel: 'Tipo de recurso',
      resourceActive: 'Recurso activo',
      createResourceBtn: 'Crear recurso',
      roomType: 'Sala',
      personType: 'Persona',
      equipmentType: 'Equipo',
      roomTypeLabel: 'Sala / Espacio',
      setupRequired: 'Configura tu negocio primero',
      setupRequiredDesc: 'Necesitas configurar tu negocio antes de agregar servicios',
    },

    reservation: {
      newTitle: 'Nueva Reserva',
      viewTitle: 'Detalles de Reserva',
      editTitle: 'Editar Reserva',
      newDesc: 'Completa los datos para crear una nueva reserva',
      viewDesc: 'Información de la reserva seleccionada',
      editDesc: 'Modifica los datos de la reserva',
      clientLabel: 'Cliente:',
      serviceLabel: 'Servicio:',
      resourceLabel: 'Recurso:',
      datetimeLabel: 'Fecha y hora:',
      roomType: 'Sala',
      personType: 'Persona',
      equipmentType: 'Equipo',
      confirmed: 'Confirmada',
      pending: 'Pendiente',
      notesLabel: 'Notas:',
      cancelReservation: 'Cancelar reserva',
      editBtn: 'Editar',
      clientSelect: 'Cliente',
      loading: 'Cargando...',
      selectClient: 'Selecciona un cliente',
      noClients: 'No hay clientes registrados',
      serviceSelect: 'Servicio',
      selectService: 'Selecciona un servicio',
      noServices: 'No hay servicios registrados',
      resourceSelect: 'Recurso',
      resourceOptional: '(opcional)',
      noResource: 'Sin recurso asignado',
      datetimeInput: 'Fecha y Hora',
      notesOptional: 'Notas (opcional)',
      notesPlaceholder: 'Agrega notas adicionales...',
      cancelBtn: 'Cancelar',
      createBtn: 'Crear reserva',
      saveBtn: 'Guardar cambios',
      durationInfo: 'Duración:',
      durationEnd: 'min — la reserva terminará a las',
      businessClosed: 'El negocio no trabaja ese día',
      businessOpensAt: 'El negocio abre a las',
      reservationAfterClose: 'La reserva terminaría después del cierre',
    },

    onboarding: {
      title: 'Bienvenido a iPlannit',
      subtitle: 'Completa estos pasos para comenzar a recibir reservas',
      hide: 'Ocultar',
      progress: 'Progreso',
      of: 'de',
      completed: 'completados',
      start: 'Comenzar',
      steps: {
        business: { title: 'Configura tu negocio', desc: 'Agrega el nombre y zona horaria de tu negocio' },
        services: { title: 'Crea tus servicios', desc: 'Define los servicios que ofreces y sus precios' },
        clients: { title: 'Agrega clientes', desc: 'Registra a tus primeros clientes' },
        reservations: { title: 'Crea tu primera reserva', desc: 'Programa tu primera cita' },
      },
    },

    settings: {
      title: 'Configuracion',
      subtitle: 'Administra tu perfil, negocio y preferencias',
      profileTab: 'Perfil',
      businessTab: 'Negocio',
      notificationsTab: 'Alertas',
      planTab: 'Plan',
      profileTitle: 'Perfil de Usuario',
      profileDesc: 'Actualiza tu informacion personal',
      changePhoto: 'Cambiar foto',
      photoHint: 'JPG, PNG o GIF. Maximo 2MB.',
      fullName: 'Nombre completo',
      emailLabel: 'Correo electronico',
      emailHint: 'El correo no puede ser cambiado',
      securityTitle: 'Seguridad',
      changePassword: 'Cambiar contrasena',
      lastUpdated: 'Ultima actualizacion hace 3 meses',
      businessTitle: 'Informacion del Negocio',
      businessDesc: 'Configura los datos de tu empresa',
      businessName: 'Nombre del negocio',
      timezone: 'Zona horaria',
      address: 'Direccion',
      addressPlaceholder: 'Direccion de tu negocio',
      phone: 'Telefono',
      phonePlaceholder: '+51 1 234 5678',
      contactEmail: 'Email de contacto',
      contactEmailPlaceholder: 'contacto@tunegocio.com',
      hoursTitle: 'Horario de Atencion',
      hoursDesc: 'Define los horarios en que tu negocio esta disponible',
      closed: 'Cerrado',
      to: 'a',
      notifTitle: 'Notificaciones por Email',
      notifDesc: 'Configura que notificaciones deseas recibir',
      confirmations: 'Confirmaciones de reserva',
      confirmationsDesc: 'Recibir email cuando se crea una nueva reserva',
      reminders: 'Recordatorios',
      remindersDesc: 'Enviar recordatorios a clientes antes de su cita',
      reminderTiming: 'Anticipacion del recordatorio',
      cancellations: 'Cancelaciones',
      cancellationsDesc: 'Recibir email cuando una reserva es cancelada',
      planTitle: 'Plan Actual',
      freePlanDesc: 'Estas en el plan gratuito',
      premiumPlanDesc: 'Disfrutas del plan premium',
      freePlanName: 'Plan Gratuito',
      premiumPlanName: 'Plan Premium',
      freeFeatures: 'Funciones básicas limitadas',
      premiumFeatures: '$20/mes - Acceso completo a todas las funciones',
      activeStatus: 'Activo',
      upgradePremium: 'Actualizar a Premium',
      premiumFeaturesTitle: 'Características Premium',
      createBusinessTitle: 'Crear Negocio',
      createBusinessDesc: 'Aún no tienes un negocio configurado. Crea uno para comenzar.',
      createBusinessBtn: 'Crear negocio',
      reminderH1: '1 hora antes',
      reminderH2: '2 horas antes',
      reminderH24: '24 horas antes',
      reminderH48: '48 horas antes',
      days: {
        monday: 'Lunes',
        tuesday: 'Martes',
        wednesday: 'Miercoles',
        thursday: 'Jueves',
        friday: 'Viernes',
        saturday: 'Sabado',
        sunday: 'Domingo',
      },
      premiumFeaturesList: [
        'Analisis y reportes avanzados',
        'Historial completo de clientes',
        'Graficos de demanda y horas pico',
        'Reportes financieros',
        'Exportacion de datos',
        'Soporte prioritario',
      ],
    },

    mobileNav: {
      openMenu: 'Abrir menu',
      menuTitle: 'Menu de navegacion',
      menu: 'Menu',
      setupBusiness: 'Configurar negocio',
      setupBusinessCta: 'Toca para comenzar',
      premium: 'Plan Premium',
      signOut: 'Cerrar sesion',
      defaultUser: 'Usuario',
    },
  },

  en: {
    locale: 'en-US',
    nav: {
      dashboard: 'Dashboard',
      calendar: 'Calendar',
      services: 'Services',
      clients: 'Clients',
      settings: 'Settings',
    },
    saveChanges: 'Save changes',
    signOut: 'Sign out',
    changesSaved: 'Changes saved',
    saveError: 'Error saving',
    welcome: 'Welcome',
    upgradePlan: 'Upgrade',
    language: { label: 'Language', es: 'Spanish', en: 'English' },

    dashboard: {
      title: 'Dashboard',
      subtitle: 'Manage your reservations and appointments',
      viewCalendar: 'View Calendar',
      reservationsToday: 'Reservations Today',
      appointmentsSubtitle: 'Scheduled appointments for today',
      businessCard: 'Business',
      notConfigured: 'Not configured',
      planCard: 'Plan',
      premium: 'Premium',
      free: 'Free',
      allFeatures: 'All features',
      basicAccess: 'Basic access',
      userCard: 'User',
      activeAccount: 'Active account',
      newReservation: 'New Reservation',
      createAppointment: 'Create a new appointment for your client',
      goToCalendar: 'Go to Calendar',
      clientsCard: 'Clients',
      manageClients: 'Manage your client list',
      viewClients: 'View Clients',
      servicesCard: 'Services',
      configureServices: 'Configure your services',
      viewServices: 'View Services',
      freePlan: 'Free Plan',
      reservationsWord: 'reservations today',
      upgrade: 'Upgrade',
    },

    calendar: {
      title: 'Calendar',
      subtitle: 'Manage your reservations and appointments',
      view: 'View',
      day: 'Day',
      week: 'Week',
      month: 'Month',
      newReservation: 'New Reservation',
      newShort: 'New',
      today: 'Today',
      noReservationsToday: 'No reservations for today',
      unknownClient: 'Unknown client',
      unknownService: 'Unknown service',
      setupRequired: 'Set up your business first',
      setupRequiredDesc: 'You need to set up your business before creating reservations',
    },

    clients: {
      title: 'Clients',
      subtitle: 'Manage your client base',
      newClient: 'New Client',
      totalClients: 'Total Clients',
      newThisMonth: 'New this month',
      withActiveReservations: 'With active reservations',
      search: 'Search clients...',
      clientCol: 'Client',
      contactCol: 'Contact',
      reservationsCol: 'Reservations',
      sinceCol: 'Since',
      notFound: 'No clients found',
      editTitle: 'Edit Client',
      newTitle: 'New Client',
      editDesc: 'Update the client details',
      newDesc: 'Add a new client to your database',
      fullName: 'Full name',
      namePlaceholder: 'Client name',
      emailLabel: 'Email address',
      emailPlaceholder: 'client@email.com',
      phoneLabel: 'Phone (optional)',
      phonePlaceholder: '+1 999 999 9999',
      notesLabel: 'Notes (optional)',
      notesPlaceholder: 'Important notes about the client...',
      cancelBtn: 'Cancel',
      createBtn: 'Create client',
      saveBtn: 'Save changes',
      detailTitle: 'Client Details',
      editBtn: 'Edit',
      viewDetailsBtn: 'View details',
      deleteBtn: 'Delete',
      reservationHistory: 'Reservation History',
      noReservations: 'This client has no reservations',
      premiumRequired: 'Reservation history is available on the Premium plan',
      upgradePremium: 'Upgrade to Premium',
      reservationsWord: 'reservations',
      confirmed: 'Confirmed',
      cancelled: 'Cancelled',
      rescheduled: 'Rescheduled',
      setupRequired: 'Set up your business first',
      setupRequiredDesc: 'You need to set up your business before adding clients',
    },

    services: {
      title: 'Services & Resources',
      subtitle: 'Manage the services you offer and available resources',
      servicesTab: 'Services',
      resourcesTab: 'Resources',
      searchServices: 'Search services...',
      searchResources: 'Search resources...',
      newService: 'New Service',
      newResource: 'New Resource',
      serviceCol: 'Service',
      durationCol: 'Duration',
      priceCol: 'Price',
      statusCol: 'Status',
      active: 'Active',
      inactive: 'Inactive',
      edit: 'Edit',
      delete: 'Delete',
      notFoundServices: 'No services found',
      notFoundResources: 'No resources found',
      editServiceTitle: 'Edit Service',
      newServiceTitle: 'New Service',
      editServiceDesc: 'Update the service details',
      newServiceDesc: 'Add a new service to your catalog',
      nameLabel: 'Name',
      namePlaceholder: 'Ex: General Consultation',
      descLabel: 'Description',
      descPlaceholder: 'Service description...',
      durationLabel: 'Duration (minutes)',
      priceLabel: 'Price (optional)',
      colorLabel: 'Color',
      serviceActive: 'Service active',
      cancelBtn: 'Cancel',
      createServiceBtn: 'Create service',
      saveBtn: 'Save changes',
      editResourceTitle: 'Edit Resource',
      newResourceTitle: 'New Resource',
      editResourceDesc: 'Update the resource details',
      newResourceDesc: 'Add a new resource (room, person, equipment)',
      resourceNamePlaceholder: 'Ex: Office 1',
      resourceDescPlaceholder: 'Resource description...',
      resourceTypeLabel: 'Resource type',
      resourceActive: 'Resource active',
      createResourceBtn: 'Create resource',
      roomType: 'Room',
      personType: 'Person',
      equipmentType: 'Equipment',
      roomTypeLabel: 'Room / Space',
      setupRequired: 'Set up your business first',
      setupRequiredDesc: 'You need to set up your business before adding services',
    },

    reservation: {
      newTitle: 'New Reservation',
      viewTitle: 'Reservation Details',
      editTitle: 'Edit Reservation',
      newDesc: 'Fill in the details to create a new reservation',
      viewDesc: 'Information about the selected reservation',
      editDesc: 'Update the reservation details',
      clientLabel: 'Client:',
      serviceLabel: 'Service:',
      resourceLabel: 'Resource:',
      datetimeLabel: 'Date and time:',
      roomType: 'Room',
      personType: 'Person',
      equipmentType: 'Equipment',
      confirmed: 'Confirmed',
      pending: 'Pending',
      notesLabel: 'Notes:',
      cancelReservation: 'Cancel reservation',
      editBtn: 'Edit',
      clientSelect: 'Client',
      loading: 'Loading...',
      selectClient: 'Select a client',
      noClients: 'No clients registered',
      serviceSelect: 'Service',
      selectService: 'Select a service',
      noServices: 'No services registered',
      resourceSelect: 'Resource',
      resourceOptional: '(optional)',
      noResource: 'No resource assigned',
      datetimeInput: 'Date and Time',
      notesOptional: 'Notes (optional)',
      notesPlaceholder: 'Add additional notes...',
      cancelBtn: 'Cancel',
      createBtn: 'Create reservation',
      saveBtn: 'Save changes',
      durationInfo: 'Duration:',
      durationEnd: 'min — the reservation will end at',
      businessClosed: 'The business does not operate on that day',
      businessOpensAt: 'The business opens at',
      reservationAfterClose: 'The reservation would end after closing time',
    },

    onboarding: {
      title: 'Welcome to iPlannit',
      subtitle: 'Complete these steps to start receiving reservations',
      hide: 'Hide',
      progress: 'Progress',
      of: 'of',
      completed: 'completed',
      start: 'Get started',
      steps: {
        business: { title: 'Set up your business', desc: 'Add your business name and timezone' },
        services: { title: 'Create your services', desc: 'Define the services you offer and their prices' },
        clients: { title: 'Add clients', desc: 'Register your first clients' },
        reservations: { title: 'Create your first reservation', desc: 'Schedule your first appointment' },
      },
    },

    settings: {
      title: 'Settings',
      subtitle: 'Manage your profile, business, and preferences',
      profileTab: 'Profile',
      businessTab: 'Business',
      notificationsTab: 'Notifications',
      planTab: 'Plan',
      profileTitle: 'User Profile',
      profileDesc: 'Update your personal information',
      changePhoto: 'Change photo',
      photoHint: 'JPG, PNG or GIF. Max 2MB.',
      fullName: 'Full name',
      emailLabel: 'Email address',
      emailHint: 'Email address cannot be changed',
      securityTitle: 'Security',
      changePassword: 'Change password',
      lastUpdated: 'Last updated 3 months ago',
      businessTitle: 'Business Information',
      businessDesc: 'Configure your company details',
      businessName: 'Business name',
      timezone: 'Timezone',
      address: 'Address',
      addressPlaceholder: 'Your business address',
      phone: 'Phone',
      phonePlaceholder: '+1 234 567 8900',
      contactEmail: 'Contact email',
      contactEmailPlaceholder: 'contact@yourbusiness.com',
      hoursTitle: 'Business Hours',
      hoursDesc: 'Define the hours your business is available',
      closed: 'Closed',
      to: 'to',
      notifTitle: 'Email Notifications',
      notifDesc: 'Configure which notifications you want to receive',
      confirmations: 'Reservation confirmations',
      confirmationsDesc: 'Receive email when a new reservation is created',
      reminders: 'Reminders',
      remindersDesc: 'Send reminders to clients before their appointment',
      reminderTiming: 'Reminder timing',
      cancellations: 'Cancellations',
      cancellationsDesc: 'Receive email when a reservation is cancelled',
      planTitle: 'Current Plan',
      freePlanDesc: 'You are on the free plan',
      premiumPlanDesc: 'You are on the premium plan',
      freePlanName: 'Free Plan',
      premiumPlanName: 'Premium Plan',
      freeFeatures: 'Basic limited features',
      premiumFeatures: '$20/month - Full access to all features',
      activeStatus: 'Active',
      upgradePremium: 'Upgrade to Premium',
      premiumFeaturesTitle: 'Premium Features',
      createBusinessTitle: 'Create Business',
      createBusinessDesc: "You don't have a business configured yet. Create one to get started.",
      createBusinessBtn: 'Create business',
      reminderH1: '1 hour before',
      reminderH2: '2 hours before',
      reminderH24: '24 hours before',
      reminderH48: '48 hours before',
      days: {
        monday: 'Monday',
        tuesday: 'Tuesday',
        wednesday: 'Wednesday',
        thursday: 'Thursday',
        friday: 'Friday',
        saturday: 'Saturday',
        sunday: 'Sunday',
      },
      premiumFeaturesList: [
        'Advanced analytics and reports',
        'Complete client history',
        'Demand and peak hour graphs',
        'Financial reports',
        'Data export',
        'Priority support',
      ],
    },

    mobileNav: {
      openMenu: 'Open menu',
      menuTitle: 'Navigation menu',
      menu: 'Menu',
      setupBusiness: 'Set up business',
      setupBusinessCta: 'Tap to get started',
      premium: 'Premium Plan',
      signOut: 'Sign out',
      defaultUser: 'User',
    },
  },
}

export type Translations = typeof TRANSLATIONS['es']

type LanguageContextType = {
  language: Language
  setLanguage: (lang: Language) => void
  locale: string
  t: Translations
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('es')

  useEffect(() => {
    const saved = localStorage.getItem('app-language') as Language | null
    if (saved === 'es' || saved === 'en') {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('app-language', lang)
  }

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage,
      locale: TRANSLATIONS[language].locale,
      t: TRANSLATIONS[language],
    }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}
