'use client'

import React, { createContext, useContext, useState, useEffect, useRef } from 'react'
import { useAuthContext } from '@/context/auth-context'
import { supabase } from '@/lib/supabase/client'

export type Language = 'es' | 'en'

const TRANSLATIONS = {
  es: {
    locale: 'es-ES',
    nav: {
      dashboard: 'Dashboard',
      calendar: 'Calendario',
      services: 'Servicios',
      clients: 'Clientes',
      analytics: 'Reportes',
      settings: 'Configuracion',
    },
    // Root-level keys used by settings (backward compat)
    saveChanges: 'Guardar cambios',
    signOut: 'Cerrar sesion',
    changesSaved: 'Cambios guardados',
    saveError: 'Error al guardar',
    welcome: 'Bienvenido',
    upgradePlan: 'Actualizar',
    expandSidebar: 'Expandir menu',
    collapseSidebar: 'Colapsar menu',
    language: { label: 'Idioma', es: 'Espanol', en: 'English' },

    dashboard: {
      title: 'Dashboard',
      subtitle: 'Gestiona tus reservas y citas',
      viewCalendar: 'Ver Calendario',
      reservationsToday: 'Reservas Hoy',
      appointmentsSubtitle: 'Citas programadas para hoy',
      vsYesterday: 'vs. ayer',
      sameAsYesterday: 'Igual que ayer',
      businessCard: 'Negocio',
      notConfigured: 'Sin configurar',
      planCard: 'Plan',
      premium: 'Premium',
      free: 'Gratuito',
      allFeatures: 'Todas las funciones',
      basicAccess: 'Acceso básico',
      userCard: 'Usuario',
      activeAccount: 'Cuenta activa',
      newReservation: 'Nueva Reserva',
      createAppointment: 'Crea una nueva cita para tu cliente',
      goToCalendar: 'Ir al Calendario',
      noReservationsTodayTitle: 'No tienes reservas para hoy',
      noReservationsTodayDesc: 'Cuando crees una, aparecerá aquí',
      viewAllReservations: 'Ver todas',
      clientsCard: 'Clientes',
      manageClients: 'Gestiona tu lista de clientes',
      viewClients: 'Ver Clientes',
      servicesCard: 'Servicios',
      configureServices: 'Configura tus servicios',
      viewServices: 'Ver Servicios',
      freePlan: 'Plan Gratuito',
      reservationsWord: 'reservas hoy',
      upgrade: 'Actualizar',
    },

    calendar: {
      title: 'Calendario',
      subtitle: 'Gestiona tus reservas y citas',
      view: 'Vista',
      day: 'Día',
      week: 'Semana',
      month: 'Mes',
      newReservation: 'Nueva Reserva',
      newShort: 'Nueva',
      today: 'Hoy',
      noReservationsToday: 'No hay reservas para hoy',
      unknownClient: 'Cliente desconocido',
      unknownService: 'Servicio desconocido',
      setupRequired: 'Configura tu negocio primero',
      setupRequiredDesc: 'Necesitas configurar tu negocio antes de crear reservas',
      loadingMore: 'Cargando más reservas...',
    },

    clients: {
      title: 'Clientes',
      subtitle: 'Administra tu base de clientes',
      newClient: 'Nuevo Cliente',
      totalClients: 'Total Clientes',
      newThisMonth: 'Nuevos este mes',
      inactiveClients: 'Clientes inactivos',
      inactiveClientsHint: '+60 dias sin reservar',
      search: 'Buscar clientes...',
      clientCol: 'Cliente',
      contactCol: 'Contacto',
      reservationsCol: 'Reservas',
      lastVisitCol: 'Ultima visita',
      neverVisited: 'Sin visitas',
      sendWhatsapp: 'Escribir por WhatsApp',
      notFound: 'No se encontraron clientes',
      editTitle: 'Editar Cliente',
      newTitle: 'Nuevo Cliente',
      editDesc: 'Modifica los datos del cliente',
      newDesc: 'Agrega un nuevo cliente a tu base de datos',
      fullName: 'Nombre completo',
      namePlaceholder: 'Nombre del cliente',
      emailLabel: 'Correo electronico',
      emailPlaceholder: 'cliente@email.com',
      phoneLabel: 'Telefono (opcional)',
      phonePlaceholder: '+51 999 999 999',
      notesLabel: 'Notas (opcional)',
      notesPlaceholder: 'Notas importantes sobre el cliente...',
      cancelBtn: 'Cancelar',
      createBtn: 'Crear cliente',
      saveBtn: 'Guardar cambios',
      detailTitle: 'Detalles del Cliente',
      editBtn: 'Editar',
      viewDetailsBtn: 'Ver detalles',
      deleteBtn: 'Eliminar',
      reservationHistory: 'Historial de Reservas',
      noReservations: 'Este cliente no tiene reservas',
      premiumRequired: 'El historial de reservas esta disponible en el plan Premium',
      upgradePremium: 'Actualizar a Premium',
      reservationsWord: 'reservas',
      confirmed: 'Confirmada',
      cancelled: 'Cancelada',
      pending: 'Pendiente',
      completed: 'Completada',
      setupRequired: 'Configura tu negocio primero',
      setupRequiredDesc: 'Necesitas configurar tu negocio antes de agregar clientes',
    },

    services: {
      title: 'Servicios y Recursos',
      subtitle: 'Administra los servicios que ofreces y los recursos disponibles',
      servicesTab: 'Servicios',
      resourcesTab: 'Recursos',
      searchServices: 'Buscar servicios...',
      searchResources: 'Buscar recursos...',
      newService: 'Nuevo Servicio',
      newResource: 'Nuevo Recurso',
      serviceCol: 'Servicio',
      durationCol: 'Duracion',
      priceCol: 'Precio',
      statusCol: 'Estado',
      active: 'Activo',
      inactive: 'Inactivo',
      edit: 'Editar',
      delete: 'Eliminar',
      deleteServiceTitle: '¿Eliminar este servicio?',
      deleteServiceDesc: 'Esta acción no se puede deshacer. También se eliminarán todas las reservas que hayan usado este servicio.',
      deleteResourceTitle: '¿Eliminar este recurso?',
      deleteResourceDesc: 'Esta acción no se puede deshacer. Las reservas existentes se conservarán, pero quedarán sin este recurso asignado.',
      confirmDelete: 'Sí, eliminar',
      deleting: 'Eliminando...',
      notFoundServices: 'No se encontraron servicios',
      notFoundResources: 'No se encontraron recursos',
      editServiceTitle: 'Editar Servicio',
      newServiceTitle: 'Nuevo Servicio',
      editServiceDesc: 'Modifica los datos del servicio',
      newServiceDesc: 'Agrega un nuevo servicio a tu catalogo',
      nameLabel: 'Nombre',
      namePlaceholder: 'Ej: Consulta General',
      descLabel: 'Descripcion',
      descPlaceholder: 'Descripcion del servicio...',
      durationLabel: 'Duracion (minutos)',
      priceLabel: 'Precio (opcional)',
      colorLabel: 'Color',
      serviceActive: 'Servicio activo',
      cancelBtn: 'Cancelar',
      createServiceBtn: 'Crear servicio',
      saveBtn: 'Guardar cambios',
      editResourceTitle: 'Editar Recurso',
      newResourceTitle: 'Nuevo Recurso',
      editResourceDesc: 'Modifica los datos del recurso',
      newResourceDesc: 'Agrega un nuevo recurso (sala, persona, equipo o virtual)',
      resourcesExplainer: 'Los recursos son las salas, personas, equipos o enlaces virtuales que usas para dar tus servicios.',
      resourceNamePlaceholder: 'Ej: Consultorio 1',
      resourceDescPlaceholder: 'Descripcion del recurso...',
      resourceTypeLabel: 'Tipo de recurso',
      resourceActive: 'Recurso activo',
      createResourceBtn: 'Crear recurso',
      roomType: 'Sala',
      personType: 'Persona',
      equipmentType: 'Equipo',
      virtualType: 'Virtual',
      roomTypeLabel: 'Sala / Espacio',
      setupRequired: 'Configura tu negocio primero',
      setupRequiredDesc: 'Necesitas configurar tu negocio antes de agregar servicios',
    },

    reservation: {
      newTitle: 'Nueva Reserva',
      viewTitle: 'Detalles de Reserva',
      editTitle: 'Editar Reserva',
      newDesc: 'Completa los datos para crear una nueva reserva',
      viewDesc: 'Información de la reserva seleccionada',
      editDesc: 'Modifica los datos de la reserva',
      clientLabel: 'Cliente:',
      serviceLabel: 'Servicio:',
      resourceLabel: 'Recurso:',
      datetimeLabel: 'Fecha y hora:',
      roomType: 'Sala',
      personType: 'Persona',
      equipmentType: 'Equipo',
      virtualType: 'Virtual',
      confirmed: 'Confirmada',
      pending: 'Pendiente',
      completed: 'Completada',
      cancelled: 'Cancelada',
      markConfirmed: 'Confirmar reserva',
      markCompleted: 'Marcar como completada',
      notesLabel: 'Notas:',
      cancelReservation: 'Cancelar reserva',
      editBtn: 'Editar',
      clientSelect: 'Cliente',
      loading: 'Cargando...',
      selectClient: 'Selecciona un cliente',
      noClients: 'No hay clientes registrados',
      serviceSelect: 'Servicio',
      selectService: 'Selecciona un servicio',
      noServices: 'No hay servicios registrados',
      resourceSelect: 'Recurso',
      resourceOptional: '(opcional)',
      noResource: 'Sin recurso asignado',
      datetimeInput: 'Fecha y Hora',
      notesOptional: 'Notas (opcional)',
      notesPlaceholder: 'Agrega notas adicionales...',
      cancelBtn: 'Cancelar',
      createBtn: 'Crear reserva',
      saveBtn: 'Guardar cambios',
      durationInfo: 'Duración:',
      durationEnd: 'min — la reserva terminará a las',
      businessClosed: 'El negocio no trabaja ese día',
      businessOpensAt: 'El negocio abre a las',
      reservationAfterClose: 'La reserva terminaría después del cierre',
      timeConflict: 'Ese horario ya está reservado para el recurso seleccionado',
      repeatLabel: 'Repetir',
      repeatDaysLabel: 'Días de la semana',
      sessionCountLabel: 'Cantidad de sesiones',
      repeatHint: 'Se crearán {count} sesiones en los días seleccionados, empezando por la fecha elegida.',
      repeatDaysRequired: 'Selecciona al menos un día para repetir',
      seriesAllConflicted: 'No se pudo crear ninguna sesión: todos los horarios elegidos ya estaban ocupados.',
      seriesPartialTitle: 'Se crearon {created} de {total} sesiones',
      seriesPartialDesc: 'Estas fechas no se pudieron crear porque el horario ya estaba ocupado:',
      understood: 'Entendido',
      partOfSeries: 'Esta reserva es parte de una serie recurrente',
      seriesRemaining: 'Quedan {count} sesiones programadas',
      cancelSeriesRemaining: 'Cancelar sesiones restantes',
    },

    onboarding: {
      title: 'Bienvenido a iPlannit',
      subtitle: 'Completa estos pasos para comenzar a recibir reservas',
      hide: 'Ocultar',
      progress: 'Progreso',
      of: 'de',
      completed: 'completados',
      start: 'Comenzar',
      steps: {
        business: { title: 'Configura tu negocio', desc: 'Agrega el nombre y zona horaria de tu negocio' },
        services: { title: 'Crea tus servicios', desc: 'Define los servicios que ofreces y sus precios' },
        clients: { title: 'Agrega clientes', desc: 'Registra a tus primeros clientes' },
        reservations: { title: 'Crea tu primera reserva', desc: 'Programa tu primera cita' },
      },
    },

    settings: {
      title: 'Configuracion',
      subtitle: 'Administra tu perfil, negocio y preferencias',
      profileTab: 'Perfil',
      businessTab: 'Negocio',
      notificationsTab: 'Alertas',
      planTab: 'Plan',
      profileTitle: 'Perfil de Usuario',
      profileDesc: 'Actualiza tu informacion personal',
      changePhoto: 'Cambiar foto',
      photoHint: 'JPG, PNG o GIF. Maximo 2MB.',
      photoUploading: 'Subiendo...',
      photoInvalidType: 'El archivo debe ser una imagen',
      photoTooLarge: 'La imagen no debe superar 2MB',
      photoUploadError: 'No se pudo subir la foto. Intenta de nuevo.',
      fullName: 'Nombre completo',
      emailLabel: 'Correo electronico',
      emailHint: 'El correo no puede ser cambiado',
      securityTitle: 'Seguridad',
      changePassword: 'Cambiar contrasena',
      lastUpdated: 'Ultima actualizacion hace 3 meses',
      businessTitle: 'Informacion del Negocio',
      businessDesc: 'Configura los datos de tu empresa',
      businessName: 'Nombre del negocio',
      timezone: 'Zona horaria',
      address: 'Direccion',
      addressPlaceholder: 'Direccion de tu negocio',
      phone: 'Telefono',
      phonePlaceholder: '+51 1 234 5678',
      contactEmail: 'Email de contacto',
      contactEmailPlaceholder: 'contacto@tunegocio.com',
      hoursTitle: 'Horario de Atencion',
      hoursDesc: 'Define los horarios en que tu negocio esta disponible',
      closed: 'Cerrado',
      to: 'a',
      notifTitle: 'Notificaciones por Email',
      notifDesc: 'Configura que notificaciones deseas recibir',
      confirmations: 'Confirmaciones de reserva',
      confirmationsDesc: 'Recibir email cuando se crea una nueva reserva',
      reminders: 'Recordatorios',
      remindersDesc: 'Enviar recordatorios a clientes antes de su cita',
      reminderTiming: 'Anticipacion del recordatorio',
      cancellations: 'Cancelaciones',
      cancellationsDesc: 'Recibir email cuando una reserva es cancelada',
      planTitle: 'Plan Actual',
      freePlanDesc: 'Estas en el plan gratuito',
      premiumPlanDesc: 'Disfrutas del plan premium',
      freePlanName: 'Plan Gratuito',
      premiumPlanName: 'Plan Premium',
      freeFeatures: 'Funciones básicas limitadas',
      premiumFeatures: '$20/mes - Acceso completo a todas las funciones',
      activeStatus: 'Activo',
      upgradePremium: 'Actualizar a Premium',
      premiumFeaturesTitle: 'Características Premium',
      createBusinessTitle: 'Crear Negocio',
      createBusinessDesc: 'Aún no tienes un negocio configurado. Crea uno para comenzar.',
      createBusinessBtn: 'Crear negocio',
      reminderH1: '1 hora antes',
      reminderH2: '2 horas antes',
      reminderH24: '24 horas antes',
      reminderH48: '48 horas antes',
      days: {
        monday: 'Lunes',
        tuesday: 'Martes',
        wednesday: 'Miercoles',
        thursday: 'Jueves',
        friday: 'Viernes',
        saturday: 'Sabado',
        sunday: 'Domingo',
      },
      premiumFeaturesList: [
        'Analisis y reportes avanzados',
        'Historial completo de clientes',
        'Graficos de demanda y horas pico',
        'Reportes financieros',
        'Exportacion de datos',
        'Soporte prioritario',
      ],
    },

    mobileNav: {
      openMenu: 'Abrir menu',
      menuTitle: 'Menu de navegacion',
      menu: 'Menu',
      setupBusiness: 'Configurar negocio',
      setupBusinessCta: 'Toca para comenzar',
      premium: 'Plan Premium',
      signOut: 'Cerrar sesion',
      defaultUser: 'Usuario',
    },

    auth: {
      languageToggle: { es: 'ES', en: 'EN' },
      register: {
        title: 'Crear cuenta',
        stepPersonal: 'Ingresa tus datos personales',
        stepBusiness: 'Configura tu negocio',
        fullName: 'Nombre completo',
        fullNamePlaceholder: 'Tu nombre',
        email: 'Correo electronico',
        emailPlaceholder: 'tu@email.com',
        password: 'Contrasena',
        passwordPlaceholderMin: 'Minimo 8 caracteres',
        continueBtn: 'Continuar',
        businessName: 'Nombre de tu negocio',
        businessNamePlaceholder: 'Ej: Clinica Salud Plus',
        businessType: 'Tipo de negocio',
        businessTypePlaceholder: 'Selecciona un tipo',
        timezone: 'Zona horaria',
        timezonePlaceholder: 'Selecciona tu zona horaria',
        back: 'Atras',
        createBtn: 'Crear cuenta',
        creating: 'Creando...',
        haveAccount: 'Ya tienes una cuenta?',
        signIn: 'Inicia sesion',
        fillAllFields: 'Por favor completa todos los campos',
        passwordRequirements: 'La contraseña debe cumplir los requisitos marcados abajo',
        successTitle: '¡Cuenta creada exitosamente!',
        successDesc: 'Revisa tu correo para confirmar tu cuenta. Te llevaremos al inicio de sesión...',
        passwordStrength: { weak: 'Débil', medium: 'Media', strong: 'Fuerte' },
        passwordReq: {
          length: 'Al menos 8 caracteres',
          uppercase: 'Una letra mayúscula',
          lowercase: 'Una letra minúscula',
          number: 'Un número',
          special: 'Un símbolo (opcional)',
        },
        businessTypes: {
          coworking: 'Coworking / Espacios de trabajo',
          clinic: 'Clínica / Consultorio médico',
          dental: 'Clínica dental',
          veterinary: 'Veterinaria',
          spa: 'Spa / Centro de belleza',
          salon: 'Peluquería / Barbería',
          gym: 'Gimnasio / Estudio fitness',
          restaurant: 'Restaurante (reserva de mesas)',
          education: 'Academia / Clases particulares',
          photography: 'Estudio fotográfico',
          events: 'Salón de eventos',
          consulting: 'Consultoría / Asesoría profesional',
          professional: 'Profesional independiente',
          other: 'Otro',
        },
      },
      login: {
        title: 'Iniciar sesion',
        subtitlePassword: 'Ingresa tus credenciales para acceder a tu cuenta',
        subtitleMagic: 'Te enviaremos un link para acceder sin contraseña',
        email: 'Correo electronico',
        emailPlaceholder: 'tu@email.com',
        password: 'Contrasena',
        passwordPlaceholder: '********',
        signInBtn: 'Iniciar sesion',
        signingIn: 'Iniciando sesion...',
        sendMagicBtn: 'Enviar link de acceso',
        sendingMagic: 'Enviando link...',
        useMagicLink: 'O usa un link de acceso sin contrasena',
        usePassword: 'O usa contrasena',
        noAccount: 'No tienes una cuenta?',
        signUp: 'Registrate',
        magicLinkSent: '¡Link de acceso enviado a tu email! Revisa tu bandeja de entrada.',
        registeredWelcome: '¡Cuenta creada exitosamente! Revisa tu correo para confirmarla y luego inicia sesión.',
        forgotPassword: '¿Olvidaste tu contraseña?',
      },
      forgotPassword: {
        title: 'Recuperar contraseña',
        subtitle: 'Ingresa tu correo y te enviaremos un enlace para restablecerla',
        email: 'Correo electronico',
        emailPlaceholder: 'tu@email.com',
        sendBtn: 'Enviar enlace',
        sending: 'Enviando...',
        successTitle: 'Revisa tu correo',
        successDesc: 'Si existe una cuenta con ese correo, te enviamos un enlace para restablecer tu contraseña.',
        backToLogin: 'Volver a iniciar sesión',
      },
      resetPassword: {
        title: 'Nueva contraseña',
        subtitle: 'Elige una contraseña nueva para tu cuenta',
        newPassword: 'Nueva contraseña',
        confirmPassword: 'Confirmar contraseña',
        passwordPlaceholderMin: 'Minimo 8 caracteres',
        updateBtn: 'Actualizar contraseña',
        updating: 'Actualizando...',
        passwordsDontMatch: 'Las contraseñas no coinciden',
        passwordRequirements: 'La contraseña debe cumplir los requisitos marcados abajo',
        successTitle: '¡Contraseña actualizada!',
        successDesc: 'Te llevaremos a tu panel...',
        invalidLinkTitle: 'Enlace inválido o expirado',
        invalidLinkDesc: 'Solicita un nuevo enlace para restablecer tu contraseña.',
        requestNewLink: 'Solicitar nuevo enlace',
        timeoutTitle: 'Esto está tardando más de lo normal',
        timeoutDesc: 'Es posible que tu contraseña ya se haya actualizado. Ya tienes sesión iniciada desde este enlace, así que puedes entrar directo a tu panel. Si más tarde no puedes iniciar sesión con la nueva contraseña, usa "Olvidé mi contraseña" de nuevo.',
        goToDashboard: 'Ir a mi panel',
      },
    },

    analytics: {
      title: 'Analytics',
      subtitle: 'Entiende la demanda y el rendimiento de tu negocio',
      rangeLabel: 'Periodo',
      range7d: 'Últimos 7 días',
      range30d: 'Últimos 30 días',
      range90d: 'Últimos 90 días',
      kpiReservations: 'Reservas',
      kpiRevenue: 'Ingresos estimados',
      kpiOccupancy: 'Ocupación',
      kpiTopService: 'Servicio más popular',
      noData: 'Sin datos suficientes para este periodo',
      demandTitle: 'Demanda por día',
      demandDesc: 'Reservas por día en el periodo seleccionado',
      peakHoursTitle: 'Horas pico',
      peakHoursDesc: 'En qué horas del día se concentran tus reservas',
      topServicesTitle: 'Servicios más usados',
      topServicesDesc: 'Reservas por servicio en el periodo seleccionado',
      revenueByServiceTitle: 'Ingresos por servicio',
      revenueByServiceDesc: 'Rentabilidad estimada por servicio',
      premiumTitle: 'Analytics es una función Premium',
      premiumDesc: 'Desbloquea reportes de demanda, horas pico y servicios más rentables',
      reservationsUnit: 'reservas',
      hoursBookedOf: 'de',
      hoursUnit: 'horas reservadas',
    },
  },

  en: {
    locale: 'en-US',
    nav: {
      dashboard: 'Dashboard',
      calendar: 'Calendar',
      services: 'Services',
      clients: 'Clients',
      analytics: 'Analytics',
      settings: 'Settings',
    },
    saveChanges: 'Save changes',
    signOut: 'Sign out',
    changesSaved: 'Changes saved',
    saveError: 'Error saving',
    welcome: 'Welcome',
    upgradePlan: 'Upgrade',
    expandSidebar: 'Expand menu',
    collapseSidebar: 'Collapse menu',
    language: { label: 'Language', es: 'Spanish', en: 'English' },

    dashboard: {
      title: 'Dashboard',
      subtitle: 'Manage your reservations and appointments',
      viewCalendar: 'View Calendar',
      reservationsToday: 'Reservations Today',
      appointmentsSubtitle: 'Scheduled appointments for today',
      vsYesterday: 'vs. yesterday',
      sameAsYesterday: 'Same as yesterday',
      businessCard: 'Business',
      notConfigured: 'Not configured',
      planCard: 'Plan',
      premium: 'Premium',
      free: 'Free',
      allFeatures: 'All features',
      basicAccess: 'Basic access',
      userCard: 'User',
      activeAccount: 'Active account',
      newReservation: 'New Reservation',
      createAppointment: 'Create a new appointment for your client',
      goToCalendar: 'Go to Calendar',
      noReservationsTodayTitle: "You don't have any reservations today",
      noReservationsTodayDesc: "When you create one, it'll show up here",
      viewAllReservations: 'View all',
      clientsCard: 'Clients',
      manageClients: 'Manage your client list',
      viewClients: 'View Clients',
      servicesCard: 'Services',
      configureServices: 'Configure your services',
      viewServices: 'View Services',
      freePlan: 'Free Plan',
      reservationsWord: 'reservations today',
      upgrade: 'Upgrade',
    },

    calendar: {
      title: 'Calendar',
      subtitle: 'Manage your reservations and appointments',
      view: 'View',
      day: 'Day',
      week: 'Week',
      month: 'Month',
      newReservation: 'New Reservation',
      newShort: 'New',
      today: 'Today',
      noReservationsToday: 'No reservations for today',
      unknownClient: 'Unknown client',
      unknownService: 'Unknown service',
      setupRequired: 'Set up your business first',
      setupRequiredDesc: 'You need to set up your business before creating reservations',
      loadingMore: 'Loading more reservations...',
    },

    clients: {
      title: 'Clients',
      subtitle: 'Manage your client base',
      newClient: 'New Client',
      totalClients: 'Total Clients',
      newThisMonth: 'New this month',
      inactiveClients: 'Inactive clients',
      inactiveClientsHint: '60+ days without a booking',
      search: 'Search clients...',
      clientCol: 'Client',
      contactCol: 'Contact',
      reservationsCol: 'Reservations',
      lastVisitCol: 'Last visit',
      neverVisited: 'No visits yet',
      sendWhatsapp: 'Message on WhatsApp',
      notFound: 'No clients found',
      editTitle: 'Edit Client',
      newTitle: 'New Client',
      editDesc: 'Update the client details',
      newDesc: 'Add a new client to your database',
      fullName: 'Full name',
      namePlaceholder: 'Client name',
      emailLabel: 'Email address',
      emailPlaceholder: 'client@email.com',
      phoneLabel: 'Phone (optional)',
      phonePlaceholder: '+1 999 999 9999',
      notesLabel: 'Notes (optional)',
      notesPlaceholder: 'Important notes about the client...',
      cancelBtn: 'Cancel',
      createBtn: 'Create client',
      saveBtn: 'Save changes',
      detailTitle: 'Client Details',
      editBtn: 'Edit',
      viewDetailsBtn: 'View details',
      deleteBtn: 'Delete',
      reservationHistory: 'Reservation History',
      noReservations: 'This client has no reservations',
      premiumRequired: 'Reservation history is available on the Premium plan',
      upgradePremium: 'Upgrade to Premium',
      reservationsWord: 'reservations',
      confirmed: 'Confirmed',
      cancelled: 'Cancelled',
      pending: 'Pending',
      completed: 'Completed',
      setupRequired: 'Set up your business first',
      setupRequiredDesc: 'You need to set up your business before adding clients',
    },

    services: {
      title: 'Services & Resources',
      subtitle: 'Manage the services you offer and available resources',
      servicesTab: 'Services',
      resourcesTab: 'Resources',
      searchServices: 'Search services...',
      searchResources: 'Search resources...',
      newService: 'New Service',
      newResource: 'New Resource',
      serviceCol: 'Service',
      durationCol: 'Duration',
      priceCol: 'Price',
      statusCol: 'Status',
      active: 'Active',
      inactive: 'Inactive',
      edit: 'Edit',
      delete: 'Delete',
      deleteServiceTitle: 'Delete this service?',
      deleteServiceDesc: 'This action cannot be undone. All reservations that used this service will also be deleted.',
      deleteResourceTitle: 'Delete this resource?',
      deleteResourceDesc: 'This action cannot be undone. Existing reservations will be kept, but will no longer have this resource assigned.',
      confirmDelete: 'Yes, delete',
      deleting: 'Deleting...',
      notFoundServices: 'No services found',
      notFoundResources: 'No resources found',
      editServiceTitle: 'Edit Service',
      newServiceTitle: 'New Service',
      editServiceDesc: 'Update the service details',
      newServiceDesc: 'Add a new service to your catalog',
      nameLabel: 'Name',
      namePlaceholder: 'Ex: General Consultation',
      descLabel: 'Description',
      descPlaceholder: 'Service description...',
      durationLabel: 'Duration (minutes)',
      priceLabel: 'Price (optional)',
      colorLabel: 'Color',
      serviceActive: 'Service active',
      cancelBtn: 'Cancel',
      createServiceBtn: 'Create service',
      saveBtn: 'Save changes',
      editResourceTitle: 'Edit Resource',
      newResourceTitle: 'New Resource',
      editResourceDesc: 'Update the resource details',
      newResourceDesc: 'Add a new resource (room, person, equipment, or virtual)',
      resourcesExplainer: 'Resources are the rooms, people, equipment, or virtual links you use to deliver your services.',
      resourceNamePlaceholder: 'Ex: Office 1',
      resourceDescPlaceholder: 'Resource description...',
      resourceTypeLabel: 'Resource type',
      resourceActive: 'Resource active',
      createResourceBtn: 'Create resource',
      roomType: 'Room',
      personType: 'Person',
      equipmentType: 'Equipment',
      virtualType: 'Virtual',
      roomTypeLabel: 'Room / Space',
      setupRequired: 'Set up your business first',
      setupRequiredDesc: 'You need to set up your business before adding services',
    },

    reservation: {
      newTitle: 'New Reservation',
      viewTitle: 'Reservation Details',
      editTitle: 'Edit Reservation',
      newDesc: 'Fill in the details to create a new reservation',
      viewDesc: 'Information about the selected reservation',
      editDesc: 'Update the reservation details',
      clientLabel: 'Client:',
      serviceLabel: 'Service:',
      resourceLabel: 'Resource:',
      datetimeLabel: 'Date and time:',
      roomType: 'Room',
      personType: 'Person',
      equipmentType: 'Equipment',
      virtualType: 'Virtual',
      confirmed: 'Confirmed',
      pending: 'Pending',
      completed: 'Completed',
      cancelled: 'Cancelled',
      markConfirmed: 'Confirm reservation',
      markCompleted: 'Mark as completed',
      notesLabel: 'Notes:',
      cancelReservation: 'Cancel reservation',
      editBtn: 'Edit',
      clientSelect: 'Client',
      loading: 'Loading...',
      selectClient: 'Select a client',
      noClients: 'No clients registered',
      serviceSelect: 'Service',
      selectService: 'Select a service',
      noServices: 'No services registered',
      resourceSelect: 'Resource',
      resourceOptional: '(optional)',
      noResource: 'No resource assigned',
      datetimeInput: 'Date and Time',
      notesOptional: 'Notes (optional)',
      notesPlaceholder: 'Add additional notes...',
      cancelBtn: 'Cancel',
      createBtn: 'Create reservation',
      saveBtn: 'Save changes',
      durationInfo: 'Duration:',
      durationEnd: 'min — the reservation will end at',
      businessClosed: 'The business does not operate on that day',
      businessOpensAt: 'The business opens at',
      reservationAfterClose: 'The reservation would end after closing time',
      timeConflict: 'That time slot is already booked for the selected resource',
      repeatLabel: 'Repeat',
      repeatDaysLabel: 'Days of the week',
      sessionCountLabel: 'Number of sessions',
      repeatHint: '{count} sessions will be created on the selected days, starting from the chosen date.',
      repeatDaysRequired: 'Select at least one day to repeat',
      seriesAllConflicted: "Couldn't create any session: every chosen time slot was already booked.",
      seriesPartialTitle: 'Created {created} of {total} sessions',
      seriesPartialDesc: "These dates couldn't be created because the time slot was already booked:",
      understood: 'Got it',
      partOfSeries: 'This reservation is part of a recurring series',
      seriesRemaining: '{count} sessions remaining',
      cancelSeriesRemaining: 'Cancel remaining sessions',
    },

    onboarding: {
      title: 'Welcome to iPlannit',
      subtitle: 'Complete these steps to start receiving reservations',
      hide: 'Hide',
      progress: 'Progress',
      of: 'of',
      completed: 'completed',
      start: 'Get started',
      steps: {
        business: { title: 'Set up your business', desc: 'Add your business name and timezone' },
        services: { title: 'Create your services', desc: 'Define the services you offer and their prices' },
        clients: { title: 'Add clients', desc: 'Register your first clients' },
        reservations: { title: 'Create your first reservation', desc: 'Schedule your first appointment' },
      },
    },

    settings: {
      title: 'Settings',
      subtitle: 'Manage your profile, business, and preferences',
      profileTab: 'Profile',
      businessTab: 'Business',
      notificationsTab: 'Notifications',
      planTab: 'Plan',
      profileTitle: 'User Profile',
      profileDesc: 'Update your personal information',
      changePhoto: 'Change photo',
      photoHint: 'JPG, PNG or GIF. Max 2MB.',
      photoUploading: 'Uploading...',
      photoInvalidType: 'The file must be an image',
      photoTooLarge: 'The image must be under 2MB',
      photoUploadError: "Couldn't upload the photo. Please try again.",
      fullName: 'Full name',
      emailLabel: 'Email address',
      emailHint: 'Email address cannot be changed',
      securityTitle: 'Security',
      changePassword: 'Change password',
      lastUpdated: 'Last updated 3 months ago',
      businessTitle: 'Business Information',
      businessDesc: 'Configure your company details',
      businessName: 'Business name',
      timezone: 'Timezone',
      address: 'Address',
      addressPlaceholder: 'Your business address',
      phone: 'Phone',
      phonePlaceholder: '+1 234 567 8900',
      contactEmail: 'Contact email',
      contactEmailPlaceholder: 'contact@yourbusiness.com',
      hoursTitle: 'Business Hours',
      hoursDesc: 'Define the hours your business is available',
      closed: 'Closed',
      to: 'to',
      notifTitle: 'Email Notifications',
      notifDesc: 'Configure which notifications you want to receive',
      confirmations: 'Reservation confirmations',
      confirmationsDesc: 'Receive email when a new reservation is created',
      reminders: 'Reminders',
      remindersDesc: 'Send reminders to clients before their appointment',
      reminderTiming: 'Reminder timing',
      cancellations: 'Cancellations',
      cancellationsDesc: 'Receive email when a reservation is cancelled',
      planTitle: 'Current Plan',
      freePlanDesc: 'You are on the free plan',
      premiumPlanDesc: 'You are on the premium plan',
      freePlanName: 'Free Plan',
      premiumPlanName: 'Premium Plan',
      freeFeatures: 'Basic limited features',
      premiumFeatures: '$20/month - Full access to all features',
      activeStatus: 'Active',
      upgradePremium: 'Upgrade to Premium',
      premiumFeaturesTitle: 'Premium Features',
      createBusinessTitle: 'Create Business',
      createBusinessDesc: "You don't have a business configured yet. Create one to get started.",
      createBusinessBtn: 'Create business',
      reminderH1: '1 hour before',
      reminderH2: '2 hours before',
      reminderH24: '24 hours before',
      reminderH48: '48 hours before',
      days: {
        monday: 'Monday',
        tuesday: 'Tuesday',
        wednesday: 'Wednesday',
        thursday: 'Thursday',
        friday: 'Friday',
        saturday: 'Saturday',
        sunday: 'Sunday',
      },
      premiumFeaturesList: [
        'Advanced analytics and reports',
        'Complete client history',
        'Demand and peak hour graphs',
        'Financial reports',
        'Data export',
        'Priority support',
      ],
    },

    mobileNav: {
      openMenu: 'Open menu',
      menuTitle: 'Navigation menu',
      menu: 'Menu',
      setupBusiness: 'Set up business',
      setupBusinessCta: 'Tap to get started',
      premium: 'Premium Plan',
      signOut: 'Sign out',
      defaultUser: 'User',
    },

    auth: {
      languageToggle: { es: 'ES', en: 'EN' },
      register: {
        title: 'Create account',
        stepPersonal: 'Enter your personal details',
        stepBusiness: 'Set up your business',
        fullName: 'Full name',
        fullNamePlaceholder: 'Your name',
        email: 'Email',
        emailPlaceholder: 'you@email.com',
        password: 'Password',
        passwordPlaceholderMin: 'At least 8 characters',
        continueBtn: 'Continue',
        businessName: 'Your business name',
        businessNamePlaceholder: 'E.g. Salud Plus Clinic',
        businessType: 'Business type',
        businessTypePlaceholder: 'Select a type',
        timezone: 'Timezone',
        timezonePlaceholder: 'Select your timezone',
        back: 'Back',
        createBtn: 'Create account',
        creating: 'Creating...',
        haveAccount: 'Already have an account?',
        signIn: 'Sign in',
        fillAllFields: 'Please fill in all fields',
        passwordRequirements: 'Password must meet the requirements listed below',
        successTitle: 'Account created successfully!',
        successDesc: "Check your email to confirm your account. We'll take you to the sign-in page...",
        passwordStrength: { weak: 'Weak', medium: 'Medium', strong: 'Strong' },
        passwordReq: {
          length: 'At least 8 characters',
          uppercase: 'One uppercase letter',
          lowercase: 'One lowercase letter',
          number: 'One number',
          special: 'One symbol (optional)',
        },
        businessTypes: {
          coworking: 'Coworking / Workspaces',
          clinic: 'Clinic / Medical office',
          dental: 'Dental clinic',
          veterinary: 'Veterinary clinic',
          spa: 'Spa / Beauty center',
          salon: 'Hair salon / Barbershop',
          gym: 'Gym / Fitness studio',
          restaurant: 'Restaurant (table reservations)',
          education: 'Academy / Private lessons',
          photography: 'Photography studio',
          events: 'Event venue',
          consulting: 'Consulting / Professional advisory',
          professional: 'Independent professional',
          other: 'Other',
        },
      },
      login: {
        title: 'Sign in',
        subtitlePassword: 'Enter your credentials to access your account',
        subtitleMagic: "We'll send you a link to sign in without a password",
        email: 'Email',
        emailPlaceholder: 'you@email.com',
        password: 'Password',
        passwordPlaceholder: '********',
        signInBtn: 'Sign in',
        signingIn: 'Signing in...',
        sendMagicBtn: 'Send sign-in link',
        sendingMagic: 'Sending link...',
        useMagicLink: 'Or use a passwordless link',
        usePassword: 'Or use a password',
        noAccount: "Don't have an account?",
        signUp: 'Sign up',
        magicLinkSent: 'Sign-in link sent to your email! Check your inbox.',
        registeredWelcome: 'Account created successfully! Check your email to confirm it, then sign in.',
        forgotPassword: 'Forgot your password?',
      },
      forgotPassword: {
        title: 'Reset password',
        subtitle: "Enter your email and we'll send you a link to reset it",
        email: 'Email',
        emailPlaceholder: 'you@email.com',
        sendBtn: 'Send link',
        sending: 'Sending...',
        successTitle: 'Check your email',
        successDesc: "If an account exists for that email, we've sent a link to reset your password.",
        backToLogin: 'Back to sign in',
      },
      resetPassword: {
        title: 'New password',
        subtitle: 'Choose a new password for your account',
        newPassword: 'New password',
        confirmPassword: 'Confirm password',
        passwordPlaceholderMin: 'At least 8 characters',
        updateBtn: 'Update password',
        updating: 'Updating...',
        passwordsDontMatch: "Passwords don't match",
        passwordRequirements: 'Password must meet the requirements listed below',
        successTitle: 'Password updated!',
        successDesc: "We'll take you to your dashboard...",
        invalidLinkTitle: 'Invalid or expired link',
        invalidLinkDesc: 'Please request a new password reset link.',
        requestNewLink: 'Request new link',
        timeoutTitle: 'This is taking longer than usual',
        timeoutDesc: 'Your password may have already been updated. You\'re already signed in from this link, so you can go straight to your dashboard. If you can\'t sign in later with the new password, use "Forgot password" again.',
        goToDashboard: 'Go to my dashboard',
      },
    },

    analytics: {
      title: 'Analytics',
      subtitle: 'Understand the demand and performance of your business',
      rangeLabel: 'Period',
      range7d: 'Last 7 days',
      range30d: 'Last 30 days',
      range90d: 'Last 90 days',
      kpiReservations: 'Reservations',
      kpiRevenue: 'Estimated revenue',
      kpiOccupancy: 'Occupancy',
      kpiTopService: 'Most popular service',
      noData: 'Not enough data for this period',
      demandTitle: 'Demand by day',
      demandDesc: 'Reservations per day in the selected period',
      peakHoursTitle: 'Peak hours',
      peakHoursDesc: 'Which hours of the day your reservations cluster around',
      topServicesTitle: 'Most used services',
      topServicesDesc: 'Reservations by service in the selected period',
      revenueByServiceTitle: 'Revenue by service',
      revenueByServiceDesc: 'Estimated profitability by service',
      premiumTitle: 'Analytics is a Premium feature',
      premiumDesc: 'Unlock demand reports, peak hours, and your most profitable services',
      reservationsUnit: 'reservations',
      hoursBookedOf: 'of',
      hoursUnit: 'hours booked',
    },
  },
}

export type Translations = typeof TRANSLATIONS['es']

type LanguageContextType = {
  language: Language
  setLanguage: (lang: Language) => void
  locale: string
  t: Translations
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('es')
  const { user, profile } = useAuthContext()
  // Tracks which profile.id we've already pulled a language from, so that an
  // unrelated profile refresh (e.g. after saving your name) doesn't clobber
  // a language you just picked manually in this session.
  const syncedProfileId = useRef<string | null>(null)

  // Pre-auth / fast-paint default: whatever this browser last used.
  useEffect(() => {
    const saved = localStorage.getItem('app-language') as Language | null
    if (saved === 'es' || saved === 'en') {
      setLanguageState(saved)
    }
  }, [])

  // Once logged in, the account's saved language (set at signup or in
  // Settings) is the source of truth - it should follow the user across
  // devices/browsers, not just live in this browser's localStorage.
  useEffect(() => {
    if (!profile) {
      syncedProfileId.current = null
      return
    }
    if (profile.id === syncedProfileId.current) return
    syncedProfileId.current = profile.id
    if (profile.language === 'es' || profile.language === 'en') {
      setLanguageState(profile.language)
      localStorage.setItem('app-language', profile.language)
    }
  }, [profile])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('app-language', lang)
    if (user) {
      supabase
        .from('profiles')
        .update({ language: lang })
        .eq('id', user.id)
        .then(({ error }) => {
          if (error) console.error('[v0] Error saving language preference:', error)
        })
    }
  }

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage,
      locale: TRANSLATIONS[language].locale,
      t: TRANSLATIONS[language],
    }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}
