'use client'

import React, { createContext, useContext, useState, useEffect, useRef } from 'react'
import { useAuthContext } from '@/context/auth-context'
import { supabase } from '@/lib/supabase/client'

export type Language = 'es' | 'en'

const TRANSLATIONS = {
  es: {
    locale: 'es-ES',
    nav: {
      dashboard: 'Dashboard',
      calendar: 'Calendario',
      services: 'Servicios',
      clients: 'Clientes',
      parking: 'Cochera',
      analytics: 'Reportes',
      settings: 'Configuracion',
    },
    sidebar: {
      roleOwner: 'Dueno',
      roleAdmin: 'Administrador',
      roleSales: 'Ventas',
    },
    // Root-level keys used by settings (backward compat)
    saveChanges: 'Guardar cambios',
    signOut: 'Cerrar sesion',
    changesSaved: 'Cambios guardados',
    saveError: 'Error al guardar',
    welcome: 'Bienvenido',
    premiumFeatureTitle: 'Funcion Premium',
    premiumFeatureUnlock: 'Desbloquear',
    upgradePlan: 'Actualizar',
    expandSidebar: 'Expandir menu',
    collapseSidebar: 'Colapsar menu',
    language: { label: 'Idioma', es: 'Espanol', en: 'English' },

    dashboard: {
      title: 'Dashboard',
      subtitle: 'Gestiona tus reservas y citas',
      viewCalendar: 'Ver Calendario',
      reservationsToday: 'Reservas Hoy',
      appointmentsSubtitle: 'Citas programadas para hoy',
      vsYesterday: 'vs. ayer',
      sameAsYesterday: 'Igual que ayer',
      businessCard: 'Negocio',
      notConfigured: 'Sin configurar',
      planCard: 'Plan',
      premium: 'Premium',
      free: 'Gratuito',
      allFeatures: 'Todas las funciones',
      basicAccess: 'Acceso básico',
      userCard: 'Usuario',
      activeAccount: 'Cuenta activa',
      newReservation: 'Nueva Reserva',
      createAppointment: 'Crea una nueva cita para tu cliente',
      goToCalendar: 'Ir al Calendario',
      noReservationsTodayTitle: 'No tienes reservas para hoy',
      noReservationsTodayDesc: 'Cuando crees una, aparecerá aquí',
      viewAllReservations: 'Ver todas',
      clientsCard: 'Clientes',
      manageClients: 'Gestiona tu lista de clientes',
      viewClients: 'Ver Clientes',
      servicesCard: 'Servicios',
      configureServices: 'Configura tus servicios',
      viewServices: 'Ver Servicios',
      freePlan: 'Plan Gratuito',
      reservationsWord: 'reservas hoy',
      upgrade: 'Actualizar',
    },

    calendar: {
      title: 'Calendario',
      subtitle: 'Gestiona tus reservas y citas',
      view: 'Vista',
      day: 'Día',
      week: 'Semana',
      month: 'Mes',
      newReservation: 'Nueva Reserva',
      newShort: 'Nueva',
      newVisit: 'Nueva Visita',
      newVisitShort: 'Visita',
      today: 'Hoy',
      noReservationsToday: 'No hay reservas para hoy',
      unknownClient: 'Cliente desconocido',
      unknownService: 'Servicio desconocido',
      setupRequired: 'Configura tu negocio primero',
      setupRequiredDesc: 'Necesitas configurar tu negocio antes de crear reservas',
      loadingMore: 'Cargando más reservas...',
    },

    clients: {
      title: 'Clientes',
      subtitle: 'Administra tu base de clientes',
      newClient: 'Nuevo Cliente',
      totalClients: 'Total Clientes',
      newThisMonth: 'Nuevos este mes',
      inactiveClients: 'Clientes inactivos',
      inactiveClientsHint: '+60 dias sin reservar',
      search: 'Buscar clientes...',
      clientCol: 'Cliente',
      contactCol: 'Contacto',
      reservationsCol: 'Reservas',
      lastVisitCol: 'Ultima visita',
      neverVisited: 'Sin visitas',
      sendWhatsapp: 'Escribir por WhatsApp',
      notFound: 'No se encontraron clientes',
      editTitle: 'Editar Cliente',
      newTitle: 'Nuevo Cliente',
      editDesc: 'Modifica los datos del cliente',
      newDesc: 'Agrega un nuevo cliente a tu base de datos',
      fullName: 'Nombre completo',
      namePlaceholder: 'Nombre del cliente',
      emailLabel: 'Correo electronico',
      emailPlaceholder: 'cliente@email.com',
      phoneLabel: 'Telefono (opcional)',
      phonePlaceholder: '+51 999 999 999',
      documentTypeLabel: 'Tipo de documento',
      documentNumberLabel: 'Numero de documento',
      documentTypeDni: 'DNI',
      documentTypeRuc: 'RUC',
      documentTypeEin: 'EIN',
      documentTypePassport: 'Pasaporte',
      documentTypeOther: 'Otro',
      documentCol: 'Documento',
      notesLabel: 'Notas (opcional)',
      notesPlaceholder: 'Notas importantes sobre el cliente...',
      cancelBtn: 'Cancelar',
      createBtn: 'Crear cliente',
      saveBtn: 'Guardar cambios',
      detailTitle: 'Detalles del Cliente',
      editBtn: 'Editar',
      viewDetailsBtn: 'Ver detalles',
      deleteBtn: 'Eliminar',
      reservationHistory: 'Historial de Reservas',
      noReservations: 'Este cliente no tiene reservas',
      premiumRequired: 'El historial de reservas esta disponible en el plan Premium',
      upgradePremium: 'Actualizar a Premium',
      reservationsWord: 'reservas',
      confirmed: 'Confirmada',
      cancelled: 'Cancelada',
      pending: 'Pendiente',
      completed: 'Completada',
      noShow: 'No-show',
      noShowCount: 'no-shows',
      lateCancellationCount: 'cancelaciones tardias',
      setupRequired: 'Configura tu negocio primero',
      setupRequiredDesc: 'Necesitas configurar tu negocio antes de agregar clientes',
    },

    services: {
      title: 'Servicios y Recursos',
      subtitle: 'Administra los servicios que ofreces y los recursos disponibles',
      servicesTab: 'Servicios',
      resourcesTab: 'Recursos',
      searchServices: 'Buscar servicios...',
      searchResources: 'Buscar recursos...',
      newService: 'Nuevo Servicio',
      newResource: 'Nuevo Recurso',
      serviceCol: 'Servicio',
      durationCol: 'Duracion',
      priceCol: 'Precio',
      statusCol: 'Estado',
      active: 'Activo',
      inactive: 'Inactivo',
      edit: 'Editar',
      delete: 'Eliminar',
      deleteServiceTitle: '¿Eliminar este servicio?',
      deleteServiceDesc: 'Esta acción no se puede deshacer. También se eliminarán todas las reservas que hayan usado este servicio.',
      deleteResourceTitle: '¿Eliminar este recurso?',
      deleteResourceDesc: 'Esta acción no se puede deshacer. Las reservas existentes se conservarán, pero quedarán sin este recurso asignado.',
      confirmDelete: 'Sí, eliminar',
      deleting: 'Eliminando...',
      notFoundServices: 'No se encontraron servicios',
      notFoundResources: 'No se encontraron recursos',
      editServiceTitle: 'Editar Servicio',
      newServiceTitle: 'Nuevo Servicio',
      editServiceDesc: 'Modifica los datos del servicio',
      newServiceDesc: 'Agrega un nuevo servicio a tu catalogo',
      nameLabel: 'Nombre',
      namePlaceholder: 'Ej: Consulta General',
      descLabel: 'Descripcion',
      descPlaceholder: 'Descripcion del servicio...',
      durationLabel: 'Duracion (minutos)',
      priceLabel: 'Precio (opcional)',
      pricingModeLabel: 'Como se cobra este servicio',
      pricingModeFixed: 'Duracion fija',
      pricingModePreset: 'Opciones predefinidas',
      pricingModeHourly: 'Por hora',
      pricingModeFixedDesc: 'Todos los clientes reservan la misma duracion y precio.',
      pricingModePresetDesc: 'El cliente elige entre varias duraciones, cada una con su propio precio (ej: cabinas por 3 o 5 horas).',
      pricingModeHourlyDesc: 'El cliente elige cuantas horas quiere dentro de un rango, y el precio se calcula automatico (horas x tarifa). Ideal para alquiler de oficinas, equipos, etc.',
      durationOptionsLabel: 'Opciones de duracion',
      addDurationOption: 'Agregar duracion',
      durationOptionsRequired: 'Agrega al menos una duracion con su precio antes de guardar, o cambia el modo de precio.',
      noDurationOptionsWarning: 'Sin duraciones - no se puede reservar',
      hourlyRateLabel: 'Tarifa por hora',
      minHoursLabel: 'Minimo de horas',
      maxHoursLabel: 'Maximo de horas',
      hourlyFieldsRequired: 'Completa la tarifa, el minimo y el maximo de horas antes de guardar.',
      hourlyRangeInvalid: 'El minimo de horas no puede ser mayor que el maximo.',
      noHourlyRateWarning: 'Sin tarifa - no se puede reservar',
      perHour: '/ hora',
      fromPrice: 'Desde',
      colorLabel: 'Color',
      serviceActive: 'Servicio activo',
      cancelBtn: 'Cancelar',
      createServiceBtn: 'Crear servicio',
      saveBtn: 'Guardar cambios',
      editResourceTitle: 'Editar Recurso',
      newResourceTitle: 'Nuevo Recurso',
      editResourceDesc: 'Modifica los datos del recurso',
      newResourceDesc: 'Agrega un nuevo recurso (sala, persona, equipo o virtual)',
      resourcesExplainer: 'Los recursos son las salas, personas, equipos o enlaces virtuales que usas para dar tus servicios.',
      resourceNamePlaceholder: 'Ej: Consultorio 1',
      resourceDescPlaceholder: 'Descripcion del recurso...',
      resourceTypeLabel: 'Tipo de recurso',
      resourceActive: 'Recurso activo',
      createResourceBtn: 'Crear recurso',
      roomType: 'Sala',
      personType: 'Persona',
      equipmentType: 'Equipo',
      virtualType: 'Virtual',
      roomTypeLabel: 'Sala / Espacio',
      setupRequired: 'Configura tu negocio primero',
      setupRequiredDesc: 'Necesitas configurar tu negocio antes de agregar servicios',
      accessRestricted: 'No tienes acceso a esta seccion',
      accessRestrictedDesc: 'Tu rol (Ventas) no incluye gestion de Servicios ni Recursos.',
    },

    reservation: {
      newTitle: 'Nueva Reserva',
      viewTitle: 'Detalles de Reserva',
      editTitle: 'Editar Reserva',
      newDesc: 'Completa los datos para crear una nueva reserva',
      viewDesc: 'Información de la reserva seleccionada',
      editDesc: 'Modifica los datos de la reserva',
      clientLabel: 'Cliente:',
      serviceLabel: 'Servicio:',
      resourceLabel: 'Recurso:',
      datetimeLabel: 'Fecha y hora:',
      roomType: 'Sala',
      personType: 'Persona',
      equipmentType: 'Equipo',
      virtualType: 'Virtual',
      confirmed: 'Confirmada',
      pending: 'Pendiente',
      completed: 'Completada',
      cancelled: 'Cancelada',
      noShow: 'No-show',
      markConfirmed: 'Confirmar reserva',
      markCompleted: 'Marcar como completada',
      markNoShow: 'Marcar como no-show',
      notesLabel: 'Notas:',
      cancelReservation: 'Cancelar reserva',
      editBtn: 'Editar',
      clientSelect: 'Cliente',
      loading: 'Cargando...',
      selectClient: 'Selecciona un cliente',
      noClients: 'No hay clientes registrados',
      serviceSelect: 'Servicio',
      selectService: 'Selecciona un servicio',
      selectServiceVisit: 'Selecciona un servicio (opcional)',
      noServiceVisit: 'Sin servicio especifico',
      noServices: 'No hay servicios registrados',
      typeBooking: 'Reserva',
      typeVisit: 'Visita',
      flexibleDurationTag: 'Duracion flexible',
      hourlyTag: 'Por hora',
      hoursLabel: 'Cuantas horas',
      hoursRangeHint: 'Entre {min} y {max} horas.',
      selectDuration: 'Selecciona una duracion',
      noDurationOptions: 'Este servicio todavia no tiene duraciones configuradas',
      priceLabel: 'Precio',
      needsParkingLabel: 'Necesita cochera',
      parkingUnavailable: 'No hay espacios de cochera disponibles a esa hora.',
      parkingAssigned: 'Cochera asignada',
      resourceSelect: 'Recurso',
      resourceOptional: '(opcional)',
      noResource: 'Sin recurso asignado',
      datetimeInput: 'Fecha y Hora',
      pickDurationFirst: 'Completa la duracion del servicio para ver los horarios disponibles.',
      noSlotsAvailable: 'No hay horarios disponibles este dia. Prueba otra fecha.',
      currentTimeLabel: 'Hora actual',
      notesOptional: 'Notas (opcional)',
      notesPlaceholder: 'Agrega notas adicionales...',
      cancelBtn: 'Cancelar',
      createBtn: 'Crear reserva',
      saveBtn: 'Guardar cambios',
      durationInfo: 'Duración:',
      durationEnd: 'min — la reserva terminará a las',
      businessClosed: 'El negocio no trabaja ese día',
      businessOpensAt: 'El negocio abre a las',
      reservationAfterClose: 'La reserva terminaría después del cierre',
      timeConflict: 'Ese horario ya está reservado para el recurso seleccionado',
      repeatLabel: 'Repetir',
      repeatDaysLabel: 'Días de la semana',
      sessionCountLabel: 'Cantidad de sesiones',
      repeatHint: 'Se crearán {count} sesiones en los días seleccionados, empezando por la fecha elegida.',
      repeatDaysRequired: 'Selecciona al menos un día para repetir',
      seriesAllConflicted: 'No se pudo crear ninguna sesión: todos los horarios elegidos ya estaban ocupados.',
      seriesPartialTitle: 'Se crearon {created} de {total} sesiones',
      seriesPartialDesc: 'Estas fechas no se pudieron crear porque el horario ya estaba ocupado:',
      understood: 'Entendido',
      partOfSeries: 'Esta reserva es parte de una serie recurrente',
      seriesRemaining: 'Quedan {count} sesiones programadas',
      cancelSeriesRemaining: 'Cancelar sesiones restantes',
    },

    onboarding: {
      title: 'Bienvenido a iPlannit',
      subtitle: 'Completa estos pasos para comenzar a recibir reservas',
      hide: 'Ocultar',
      progress: 'Progreso',
      of: 'de',
      completed: 'completados',
      start: 'Comenzar',
      steps: {
        business: { title: 'Configura tu negocio', desc: 'Agrega el nombre y zona horaria de tu negocio' },
        services: { title: 'Crea tus servicios', desc: 'Define los servicios que ofreces y sus precios' },
        clients: { title: 'Agrega clientes', desc: 'Registra a tus primeros clientes' },
        reservations: { title: 'Crea tu primera reserva', desc: 'Programa tu primera cita' },
      },
    },

    settings: {
      title: 'Configuracion',
      subtitle: 'Administra tu perfil, negocio y preferencias',
      profileTab: 'Perfil',
      businessTab: 'Negocio',
      notificationsTab: 'Alertas',
      planTab: 'Plan',
      teamTab: 'Equipo',
      team: {
        featureName: 'Equipo',
        title: 'Equipo',
        desc: 'Agrega personas que operen el negocio contigo, con acceso segun su rol. Ninguno puede tocar la configuracion del negocio.',
        emailLabel: 'Correo',
        emailPlaceholder: 'correo@ejemplo.com',
        addBtn: 'Agregar',
        empty: 'Todavia no agregaste a nadie a tu equipo.',
        hint: 'La persona ya debe tener una cuenta en iPlanit. Su acceso depende de que tu plan Premium este activo.',
        added: 'Se agrego a {name}.',
        errorNotFound: 'Ese correo no tiene una cuenta en iPlanit todavia. Pidele que se registre primero.',
        errorNotPremium: 'Necesitas el plan Premium para agregar personas a tu equipo.',
        errorIsOwner: 'Ese correo ya es el dueno de este negocio.',
        errorGeneric: 'No se pudo agregar a la persona. Intenta de nuevo.',
        roleAdmin: 'Administrador',
        roleSales: 'Ventas',
        roleAdminDesc: 'Acceso operativo completo (reservas, clientes, servicios, recursos, reportes) salvo configuracion del negocio.',
        roleSalesDesc: 'Solo reservas y clientes. Sin acceso a Servicios, Recursos ni Reportes.',
      },
      profileTitle: 'Perfil de Usuario',
      profileDesc: 'Actualiza tu informacion personal',
      changePhoto: 'Cambiar foto',
      photoHint: 'JPG, PNG o GIF. Maximo 2MB.',
      photoUploading: 'Subiendo...',
      photoInvalidType: 'El archivo debe ser una imagen',
      photoTooLarge: 'La imagen no debe superar 2MB',
      photoUploadError: 'No se pudo subir la foto. Intenta de nuevo.',
      fullName: 'Nombre completo',
      emailLabel: 'Correo electronico',
      emailHint: 'El correo no puede ser cambiado',
      securityTitle: 'Seguridad',
      changePassword: 'Cambiar contrasena',
      lastUpdated: 'Ultima actualizacion hace 3 meses',
      businessTitle: 'Informacion del Negocio',
      businessDesc: 'Configura los datos de tu empresa',
      businessName: 'Nombre del negocio',
      businessCountry: 'Pais del negocio',
      countryPE: 'Peru',
      countryUS: 'Estados Unidos',
      rucLabel: 'RUC (opcional)',
      einLabel: 'EIN (opcional)',
      businessCurrency: 'Moneda del negocio',
      currencyPEN: 'Soles (S/)',
      currencyUSD: 'Dolares (US$)',
      businessCurrencyHint: 'La moneda en la que cobras a tus clientes. No tiene que coincidir con el pais del negocio.',
      cancellationPolicyLabel: 'Politica de cancelacion (horas)',
      cancellationPolicyHint: 'Cancelaciones del cliente con menos de esta anticipacion se marcan como tardias en el historial del cliente. No se cobra nada automaticamente - tu decides si aplicar una penalidad por fuera del sistema.',
      offersParkingLabel: 'Ofreces cochera',
      offersParkingDesc: 'Activa la seccion Cochera para gestionar espacios y ofrecer la opcion al reservar, interno y en tu pagina publica.',
      timezone: 'Zona horaria',
      address: 'Direccion',
      addressPlaceholder: 'Direccion de tu negocio',
      phone: 'Telefono',
      phonePlaceholder: '+51 1 234 5678',
      contactEmail: 'Email de contacto',
      contactEmailPlaceholder: 'contacto@tunegocio.com',
      slugLabel: 'Link personalizado',
      slugRequired: 'El link no puede quedar vacio.',
      slugTaken: 'Ese link ya lo esta usando otro negocio, prueba otro.',
      bookingLinkTitle: 'Link para reservas',
      bookingLinkDesc: 'Compartelo con tus clientes para que reserven solos, sin que tengas que registrar cada cita tu mismo.',
      copyLink: 'Copiar',
      linkCopied: 'Copiado',
      bookingLinkUnavailable: 'Configura el nombre de tu negocio para generar tu link de reservas.',
      hoursTitle: 'Horario de Atencion',
      hoursDesc: 'Define los horarios en que tu negocio esta disponible',
      closed: 'Cerrado',
      to: 'a',
      comingSoon: 'Proximamente',
      notifComingSoonBanner: 'Todavia no enviamos correos automaticos - estos ajustes son una vista previa de lo que viene. Por ahora, nada de esto envia notificaciones.',
      notifTitle: 'Notificaciones por Email',
      notifDesc: 'Configura que notificaciones deseas recibir',
      confirmations: 'Confirmaciones de reserva',
      confirmationsDesc: 'Recibir email cuando se crea una nueva reserva',
      reminders: 'Recordatorios',
      remindersDesc: 'Enviar recordatorios a clientes antes de su cita',
      reminderTiming: 'Anticipacion del recordatorio',
      cancellations: 'Cancelaciones',
      cancellationsDesc: 'Recibir email cuando una reserva es cancelada',
      planTitle: 'Plan Actual',
      freePlanDesc: 'Estas en el plan gratuito',
      premiumPlanDesc: 'Disfrutas del plan premium',
      freePlanName: 'Plan Gratuito',
      premiumPlanName: 'Plan Premium',
      freeFeatures: 'Funciones básicas limitadas',
      premiumFeatures: '$20/mes - Acceso completo a todas las funciones',
      activeStatus: 'Activo',
      upgradePremium: 'Actualizar a Premium',
      premiumFeaturesTitle: 'Características Premium',
      createBusinessTitle: 'Crear Negocio',
      createBusinessDesc: 'Aún no tienes un negocio configurado. Crea uno para comenzar.',
      createBusinessBtn: 'Crear negocio',
      reminderH1: '1 hora antes',
      reminderH2: '2 horas antes',
      reminderH24: '24 horas antes',
      reminderH48: '48 horas antes',
      days: {
        monday: 'Lunes',
        tuesday: 'Martes',
        wednesday: 'Miercoles',
        thursday: 'Jueves',
        friday: 'Viernes',
        saturday: 'Sabado',
        sunday: 'Domingo',
      },
      premiumFeaturesList: [
        'Analisis y reportes avanzados',
        'Historial completo de clientes',
        'Graficos de demanda y horas pico',
        'Reportes financieros',
        'Exportacion de datos',
        'Soporte prioritario',
      ],
    },

    mobileNav: {
      openMenu: 'Abrir menu',
      menuTitle: 'Menu de navegacion',
      menu: 'Menu',
      setupBusiness: 'Configurar negocio',
      setupBusinessCta: 'Toca para comenzar',
      premium: 'Plan Premium',
      signOut: 'Cerrar sesion',
      defaultUser: 'Usuario',
    },

    publicBooking: {
      notFoundTitle: 'Negocio no encontrado',
      notFoundDesc: 'Revisa el enlace, puede que ya no este disponible.',
      stepService: 'Elige un servicio',
      stepServiceDesc: 'Selecciona lo que quieres reservar',
      stepDuration: 'Elige una duracion',
      stepDurationDesc: 'Este servicio tiene distintas duraciones disponibles',
      stepHours: 'Elige cuantas horas',
      stepHoursDesc: 'El precio se calcula automatico segun las horas que elijas',
      flexibleDurationTag: 'Duracion flexible',
      hourlyTag: 'Por hora',
      perHourShort: '/hora',
      hoursLabel: 'Cuantas horas',
      hoursRangeHint: 'Entre {min} y {max} horas.',
      totalPriceLabel: 'Total',
      fromPrice: 'Desde',
      noDurationOptions: 'Este servicio todavia no tiene duraciones configuradas',
      stepResource: 'Elige una opcion',
      stepResourceDesc: 'Este servicio tiene mas de una opcion disponible',
      stepDatetime: 'Elige fecha y hora',
      stepDatetimeDesc: 'Estos son los horarios disponibles',
      stepContact: 'Tus datos',
      stepContactDesc: 'Para confirmar tu reserva',
      noServices: 'Este negocio no tiene servicios disponibles todavia.',
      back: 'Atras',
      noSlots: 'No hay horarios disponibles este dia. Prueba otra fecha.',
      continueBtn: 'Continuar',
      nameLabel: 'Nombre completo',
      emailLabel: 'Correo (opcional)',
      phoneLabel: 'Telefono (opcional)',
      notesLabel: 'Notas (opcional)',
      contactHint: 'Deja al menos un correo o telefono para que puedan contactarte.',
      confirmBtn: 'Confirmar reserva',
      pendingHint: 'El negocio revisara tu solicitud y la confirmara pronto.',
      poweredBy: 'Reservas con iPlanit',
      successTitle: 'Solicitud enviada',
      successDesc: 'El negocio confirmara tu reserva pronto.',
      errorTimeConflict: 'Ese horario ya no esta disponible. Elige otro.',
      errorNameRequired: 'Escribe tu nombre.',
      errorContactRequired: 'Deja un correo o telefono de contacto.',
      errorGeneric: 'No se pudo completar la reserva. Intenta de nuevo.',
      needsParkingLabel: '¿Vienes en auto? Reserva un espacio de cochera',
      errorParkingUnavailable: 'No hay espacios de cochera disponibles a esa hora. Puedes continuar sin cochera o elegir otro horario.',
      parkingConfirmed: 'Tienes un espacio de cochera reservado.',
      manageParkingConfirmed: 'Tienes cochera confirmada para esta cita.',
      manageLinkTitle: 'Gestiona tu cita',
      manageLinkDesc: 'Guarda este enlace: es la unica forma de cancelar tu cita sin llamarnos.',
      manageNotFoundTitle: 'Cita no encontrada',
      manageNotFoundDesc: 'Revisa el enlace, puede que ya no exista.',
      manageStatusLabel: 'Estado',
      manageDatetimeLabel: 'Fecha y hora',
      manageCancelBtn: 'Cancelar mi cita',
      manageCancelling: 'Cancelando...',
      manageCancelConfirmTitle: 'Confirmar cancelacion',
      manageCancelConfirmDesc: 'Esta accion no se puede deshacer.',
      manageCancelWindowWarning: 'Estas cancelando con menos de {hours} horas de anticipacion. Segun la politica de {business}, esto puede generar una penalidad.',
      manageAlreadyCancelled: 'Esta cita ya fue cancelada.',
      manageAlreadyCompleted: 'Esta cita ya se realizo.',
      manageAlreadyNoShow: 'Esta cita fue marcada como no-show.',
      manageCancelSuccess: 'Tu cita fue cancelada.',
      manageCancelError: 'No se pudo cancelar tu cita. Intenta de nuevo o contacta al negocio.',
      manageKeepBtn: 'No, mantener mi cita',
    },

    parking: {
      title: 'Cochera',
      subtitle: 'Gestiona los espacios de cochera que ofreces a tus clientes',
      newSpot: 'Nuevo espacio',
      setupRequired: 'Configura tu negocio primero',
      notEnabledTitle: 'Cochera no esta activada',
      notEnabledDesc: 'Activa "Ofreces cochera" en Configuracion > Negocio para gestionar espacios.',
      occupancyTitle: 'Ocupacion ahora',
      occupancyDesc: 'Espacios ocupados en este momento sobre el total activo',
      occupiedNow: 'Ocupado ahora',
      noSpots: 'Todavia no agregaste espacios de cochera',
      editSpotTitle: 'Editar espacio',
      newSpotTitle: 'Nuevo espacio de cochera',
      spotFormDesc: 'Cada espacio es una unidad de cochera independiente que un cliente puede reservar.',
      spotNameLabel: 'Nombre',
      spotNamePlaceholder: 'Ej: Espacio 1',
      createSpotBtn: 'Crear espacio',
      deleteSpotTitle: 'Eliminar espacio',
      deleteSpotDesc: 'Esta accion no se puede deshacer.',
    },

    auth: {
      languageToggle: { es: 'ES', en: 'EN' },
      register: {
        title: 'Crear cuenta',
        stepPersonal: 'Ingresa tus datos personales',
        stepBusiness: 'Configura tu negocio',
        fullName: 'Nombre completo',
        fullNamePlaceholder: 'Tu nombre',
        email: 'Correo electronico',
        emailPlaceholder: 'tu@email.com',
        password: 'Contrasena',
        passwordPlaceholderMin: 'Minimo 8 caracteres',
        continueBtn: 'Continuar',
        businessName: 'Nombre de tu negocio',
        businessNamePlaceholder: 'Ej: Clinica Salud Plus',
        businessType: 'Tipo de negocio',
        businessTypePlaceholder: 'Selecciona un tipo',
        businessCountry: 'Pais del negocio',
        businessCountryPlaceholder: 'Selecciona un pais',
        countryPE: 'Peru',
        countryUS: 'Estados Unidos',
        timezone: 'Zona horaria',
        timezonePlaceholder: 'Selecciona tu zona horaria',
        back: 'Atras',
        createBtn: 'Crear cuenta',
        creating: 'Creando...',
        skipBusiness: 'Omitir, me unire a un negocio existente',
        haveAccount: 'Ya tienes una cuenta?',
        signIn: 'Inicia sesion',
        fillAllFields: 'Por favor completa todos los campos',
        passwordRequirements: 'La contraseña debe cumplir los requisitos marcados abajo',
        successTitle: '¡Cuenta creada exitosamente!',
        successDesc: 'Revisa tu correo para confirmar tu cuenta. Te llevaremos al inicio de sesión...',
        passwordStrength: { weak: 'Débil', medium: 'Media', strong: 'Fuerte' },
        passwordReq: {
          length: 'Al menos 8 caracteres',
          uppercase: 'Una letra mayúscula',
          lowercase: 'Una letra minúscula',
          number: 'Un número',
          special: 'Un símbolo (opcional)',
        },
        businessTypes: {
          coworking: 'Coworking / Espacios de trabajo',
          clinic: 'Clínica / Consultorio médico',
          dental: 'Clínica dental',
          veterinary: 'Veterinaria',
          spa: 'Spa / Centro de belleza',
          salon: 'Peluquería / Barbería',
          gym: 'Gimnasio / Estudio fitness',
          restaurant: 'Restaurante (reserva de mesas)',
          education: 'Academia / Clases particulares',
          photography: 'Estudio fotográfico',
          events: 'Salón de eventos',
          consulting: 'Consultoría / Asesoría profesional',
          professional: 'Profesional independiente',
          other: 'Otro',
        },
      },
      login: {
        title: 'Iniciar sesion',
        subtitlePassword: 'Ingresa tus credenciales para acceder a tu cuenta',
        subtitleMagic: 'Te enviaremos un link para acceder sin contraseña',
        email: 'Correo electronico',
        emailPlaceholder: 'tu@email.com',
        password: 'Contrasena',
        passwordPlaceholder: '********',
        signInBtn: 'Iniciar sesion',
        signingIn: 'Iniciando sesion...',
        sendMagicBtn: 'Enviar link de acceso',
        sendingMagic: 'Enviando link...',
        useMagicLink: 'O usa un link de acceso sin contrasena',
        usePassword: 'O usa contrasena',
        noAccount: 'No tienes una cuenta?',
        signUp: 'Registrate',
        magicLinkSent: '¡Link de acceso enviado a tu email! Revisa tu bandeja de entrada.',
        registeredWelcome: '¡Cuenta creada exitosamente! Revisa tu correo para confirmarla y luego inicia sesión.',
        forgotPassword: '¿Olvidaste tu contraseña?',
      },
      forgotPassword: {
        title: 'Recuperar contraseña',
        subtitle: 'Ingresa tu correo y te enviaremos un enlace para restablecerla',
        email: 'Correo electronico',
        emailPlaceholder: 'tu@email.com',
        sendBtn: 'Enviar enlace',
        sending: 'Enviando...',
        successTitle: 'Revisa tu correo',
        successDesc: 'Si existe una cuenta con ese correo, te enviamos un enlace para restablecer tu contraseña.',
        backToLogin: 'Volver a iniciar sesión',
      },
      resetPassword: {
        title: 'Nueva contraseña',
        subtitle: 'Elige una contraseña nueva para tu cuenta',
        newPassword: 'Nueva contraseña',
        confirmPassword: 'Confirmar contraseña',
        passwordPlaceholderMin: 'Minimo 8 caracteres',
        updateBtn: 'Actualizar contraseña',
        updating: 'Actualizando...',
        passwordsDontMatch: 'Las contraseñas no coinciden',
        passwordRequirements: 'La contraseña debe cumplir los requisitos marcados abajo',
        successTitle: '¡Contraseña actualizada!',
        successDesc: 'Te llevaremos a tu panel...',
        invalidLinkTitle: 'Enlace inválido o expirado',
        invalidLinkDesc: 'Solicita un nuevo enlace para restablecer tu contraseña.',
        requestNewLink: 'Solicitar nuevo enlace',
        timeoutTitle: 'Esto está tardando más de lo normal',
        timeoutDesc: 'Es posible que tu contraseña ya se haya actualizado. Ya tienes sesión iniciada desde este enlace, así que puedes entrar directo a tu panel. Si más tarde no puedes iniciar sesión con la nueva contraseña, usa "Olvidé mi contraseña" de nuevo.',
        goToDashboard: 'Ir a mi panel',
      },
    },

    analytics: {
      title: 'Analytics',
      subtitle: 'Entiende la demanda y el rendimiento de tu negocio',
      rangeLabel: 'Periodo',
      range7d: 'Últimos 7 días',
      range30d: 'Últimos 30 días',
      range90d: 'Últimos 90 días',
      kpiReservations: 'Reservas',
      kpiRevenue: 'Ingresos estimados',
      kpiOccupancy: 'Ocupación',
      kpiTopService: 'Servicio más popular',
      kpiNoShowRate: 'Tasa de no-show',
      kpiVisits: 'Visitas',
      kpiVisitsDesc: 'Personas que vinieron a conocer el negocio',
      noData: 'Sin datos suficientes para este periodo',
      demandTitle: 'Demanda por día',
      demandDesc: 'Reservas por día en el periodo seleccionado',
      peakHoursTitle: 'Horas pico',
      peakHoursDesc: 'En qué horas del día se concentran tus reservas',
      topServicesTitle: 'Servicios más usados',
      topServicesDesc: 'Reservas por servicio en el periodo seleccionado',
      revenueByServiceTitle: 'Ingresos por servicio',
      revenueByServiceDesc: 'Rentabilidad estimada por servicio',
      premiumTitle: 'Analytics es una función Premium',
      premiumDesc: 'Desbloquea reportes de demanda, horas pico y servicios más rentables',
      reservationsUnit: 'reservas',
      hoursBookedOf: 'de',
      hoursUnit: 'horas reservadas',
      accessRestricted: 'No tienes acceso a esta seccion',
      accessRestrictedDesc: 'Tu rol (Ventas) no incluye Reportes.',
    },
  },

  en: {
    locale: 'en-US',
    nav: {
      dashboard: 'Dashboard',
      calendar: 'Calendar',
      services: 'Services',
      clients: 'Clients',
      parking: 'Parking',
      analytics: 'Analytics',
      settings: 'Settings',
    },
    sidebar: {
      roleOwner: 'Owner',
      roleAdmin: 'Admin',
      roleSales: 'Sales',
    },
    saveChanges: 'Save changes',
    signOut: 'Sign out',
    changesSaved: 'Changes saved',
    saveError: 'Error saving',
    welcome: 'Welcome',
    premiumFeatureTitle: 'Premium Feature',
    premiumFeatureUnlock: 'Unlock',
    upgradePlan: 'Upgrade',
    expandSidebar: 'Expand menu',
    collapseSidebar: 'Collapse menu',
    language: { label: 'Language', es: 'Spanish', en: 'English' },

    dashboard: {
      title: 'Dashboard',
      subtitle: 'Manage your reservations and appointments',
      viewCalendar: 'View Calendar',
      reservationsToday: 'Reservations Today',
      appointmentsSubtitle: 'Scheduled appointments for today',
      vsYesterday: 'vs. yesterday',
      sameAsYesterday: 'Same as yesterday',
      businessCard: 'Business',
      notConfigured: 'Not configured',
      planCard: 'Plan',
      premium: 'Premium',
      free: 'Free',
      allFeatures: 'All features',
      basicAccess: 'Basic access',
      userCard: 'User',
      activeAccount: 'Active account',
      newReservation: 'New Reservation',
      createAppointment: 'Create a new appointment for your client',
      goToCalendar: 'Go to Calendar',
      noReservationsTodayTitle: "You don't have any reservations today",
      noReservationsTodayDesc: "When you create one, it'll show up here",
      viewAllReservations: 'View all',
      clientsCard: 'Clients',
      manageClients: 'Manage your client list',
      viewClients: 'View Clients',
      servicesCard: 'Services',
      configureServices: 'Configure your services',
      viewServices: 'View Services',
      freePlan: 'Free Plan',
      reservationsWord: 'reservations today',
      upgrade: 'Upgrade',
    },

    calendar: {
      title: 'Calendar',
      subtitle: 'Manage your reservations and appointments',
      view: 'View',
      day: 'Day',
      week: 'Week',
      month: 'Month',
      newReservation: 'New Reservation',
      newShort: 'New',
      newVisit: 'New Visit',
      newVisitShort: 'Visit',
      today: 'Today',
      noReservationsToday: 'No reservations for today',
      unknownClient: 'Unknown client',
      unknownService: 'Unknown service',
      setupRequired: 'Set up your business first',
      setupRequiredDesc: 'You need to set up your business before creating reservations',
      loadingMore: 'Loading more reservations...',
    },

    clients: {
      title: 'Clients',
      subtitle: 'Manage your client base',
      newClient: 'New Client',
      totalClients: 'Total Clients',
      newThisMonth: 'New this month',
      inactiveClients: 'Inactive clients',
      inactiveClientsHint: '60+ days without a booking',
      search: 'Search clients...',
      clientCol: 'Client',
      contactCol: 'Contact',
      reservationsCol: 'Reservations',
      lastVisitCol: 'Last visit',
      neverVisited: 'No visits yet',
      sendWhatsapp: 'Message on WhatsApp',
      notFound: 'No clients found',
      editTitle: 'Edit Client',
      newTitle: 'New Client',
      editDesc: 'Update the client details',
      newDesc: 'Add a new client to your database',
      fullName: 'Full name',
      namePlaceholder: 'Client name',
      emailLabel: 'Email address',
      emailPlaceholder: 'client@email.com',
      phoneLabel: 'Phone (optional)',
      phonePlaceholder: '+1 999 999 9999',
      documentTypeLabel: 'Document type',
      documentNumberLabel: 'Document number',
      documentTypeDni: 'DNI',
      documentTypeRuc: 'RUC',
      documentTypeEin: 'EIN',
      documentTypePassport: 'Passport',
      documentTypeOther: 'Other',
      documentCol: 'Document',
      notesLabel: 'Notes (optional)',
      notesPlaceholder: 'Important notes about the client...',
      cancelBtn: 'Cancel',
      createBtn: 'Create client',
      saveBtn: 'Save changes',
      detailTitle: 'Client Details',
      editBtn: 'Edit',
      viewDetailsBtn: 'View details',
      deleteBtn: 'Delete',
      reservationHistory: 'Reservation History',
      noReservations: 'This client has no reservations',
      premiumRequired: 'Reservation history is available on the Premium plan',
      upgradePremium: 'Upgrade to Premium',
      reservationsWord: 'reservations',
      confirmed: 'Confirmed',
      cancelled: 'Cancelled',
      pending: 'Pending',
      completed: 'Completed',
      noShow: 'No-show',
      noShowCount: 'no-shows',
      lateCancellationCount: 'late cancellations',
      setupRequired: 'Set up your business first',
      setupRequiredDesc: 'You need to set up your business before adding clients',
    },

    services: {
      title: 'Services & Resources',
      subtitle: 'Manage the services you offer and available resources',
      servicesTab: 'Services',
      resourcesTab: 'Resources',
      searchServices: 'Search services...',
      searchResources: 'Search resources...',
      newService: 'New Service',
      newResource: 'New Resource',
      serviceCol: 'Service',
      durationCol: 'Duration',
      priceCol: 'Price',
      statusCol: 'Status',
      active: 'Active',
      inactive: 'Inactive',
      edit: 'Edit',
      delete: 'Delete',
      deleteServiceTitle: 'Delete this service?',
      deleteServiceDesc: 'This action cannot be undone. All reservations that used this service will also be deleted.',
      deleteResourceTitle: 'Delete this resource?',
      deleteResourceDesc: 'This action cannot be undone. Existing reservations will be kept, but will no longer have this resource assigned.',
      confirmDelete: 'Yes, delete',
      deleting: 'Deleting...',
      notFoundServices: 'No services found',
      notFoundResources: 'No resources found',
      editServiceTitle: 'Edit Service',
      newServiceTitle: 'New Service',
      editServiceDesc: 'Update the service details',
      newServiceDesc: 'Add a new service to your catalog',
      nameLabel: 'Name',
      namePlaceholder: 'Ex: General Consultation',
      descLabel: 'Description',
      descPlaceholder: 'Service description...',
      durationLabel: 'Duration (minutes)',
      priceLabel: 'Price (optional)',
      pricingModeLabel: 'How this service is priced',
      pricingModeFixed: 'Fixed duration',
      pricingModePreset: 'Preset options',
      pricingModeHourly: 'Hourly',
      pricingModeFixedDesc: 'Every client books the same duration and price.',
      pricingModePresetDesc: 'The client picks between several durations, each with its own price (e.g. cabins for 3 or 5 hours).',
      pricingModeHourlyDesc: 'The client picks how many hours they want within a range, and the price is calculated automatically (hours x rate). Ideal for office rentals, equipment, etc.',
      durationOptionsLabel: 'Duration options',
      addDurationOption: 'Add duration',
      durationOptionsRequired: 'Add at least one duration with its price before saving, or change the pricing mode.',
      noDurationOptionsWarning: "No durations - can't be booked",
      hourlyRateLabel: 'Hourly rate',
      minHoursLabel: 'Minimum hours',
      maxHoursLabel: 'Maximum hours',
      hourlyFieldsRequired: 'Fill in the rate, minimum, and maximum hours before saving.',
      hourlyRangeInvalid: "Minimum hours can't be greater than maximum hours.",
      noHourlyRateWarning: "No rate set - can't be booked",
      perHour: '/ hour',
      fromPrice: 'From',
      colorLabel: 'Color',
      serviceActive: 'Service active',
      cancelBtn: 'Cancel',
      createServiceBtn: 'Create service',
      saveBtn: 'Save changes',
      editResourceTitle: 'Edit Resource',
      newResourceTitle: 'New Resource',
      editResourceDesc: 'Update the resource details',
      newResourceDesc: 'Add a new resource (room, person, equipment, or virtual)',
      resourcesExplainer: 'Resources are the rooms, people, equipment, or virtual links you use to deliver your services.',
      resourceNamePlaceholder: 'Ex: Office 1',
      resourceDescPlaceholder: 'Resource description...',
      resourceTypeLabel: 'Resource type',
      resourceActive: 'Resource active',
      createResourceBtn: 'Create resource',
      roomType: 'Room',
      personType: 'Person',
      equipmentType: 'Equipment',
      virtualType: 'Virtual',
      roomTypeLabel: 'Room / Space',
      setupRequired: 'Set up your business first',
      setupRequiredDesc: 'You need to set up your business before adding services',
      accessRestricted: "You don't have access to this section",
      accessRestrictedDesc: 'Your role (Sales) does not include managing Services or Resources.',
    },

    reservation: {
      newTitle: 'New Reservation',
      viewTitle: 'Reservation Details',
      editTitle: 'Edit Reservation',
      newDesc: 'Fill in the details to create a new reservation',
      viewDesc: 'Information about the selected reservation',
      editDesc: 'Update the reservation details',
      clientLabel: 'Client:',
      serviceLabel: 'Service:',
      resourceLabel: 'Resource:',
      datetimeLabel: 'Date and time:',
      roomType: 'Room',
      personType: 'Person',
      equipmentType: 'Equipment',
      virtualType: 'Virtual',
      confirmed: 'Confirmed',
      pending: 'Pending',
      completed: 'Completed',
      cancelled: 'Cancelled',
      noShow: 'No-show',
      markConfirmed: 'Confirm reservation',
      markCompleted: 'Mark as completed',
      markNoShow: 'Mark as no-show',
      notesLabel: 'Notes:',
      cancelReservation: 'Cancel reservation',
      editBtn: 'Edit',
      clientSelect: 'Client',
      loading: 'Loading...',
      selectClient: 'Select a client',
      noClients: 'No clients registered',
      serviceSelect: 'Service',
      selectService: 'Select a service',
      selectServiceVisit: 'Select a service (optional)',
      noServiceVisit: 'No specific service',
      noServices: 'No services registered',
      typeBooking: 'Reservation',
      typeVisit: 'Visit',
      flexibleDurationTag: 'Flexible duration',
      hourlyTag: 'Hourly',
      hoursLabel: 'How many hours',
      hoursRangeHint: 'Between {min} and {max} hours.',
      selectDuration: 'Select a duration',
      noDurationOptions: 'This service has no durations configured yet',
      priceLabel: 'Price',
      needsParkingLabel: 'Needs parking',
      parkingUnavailable: 'No parking spots are available at that time.',
      parkingAssigned: 'Parking assigned',
      resourceSelect: 'Resource',
      resourceOptional: '(optional)',
      noResource: 'No resource assigned',
      datetimeInput: 'Date and Time',
      pickDurationFirst: 'Finish setting the service duration to see available times.',
      noSlotsAvailable: 'No time slots available this day. Try another date.',
      currentTimeLabel: 'Current time',
      notesOptional: 'Notes (optional)',
      notesPlaceholder: 'Add additional notes...',
      cancelBtn: 'Cancel',
      createBtn: 'Create reservation',
      saveBtn: 'Save changes',
      durationInfo: 'Duration:',
      durationEnd: 'min — the reservation will end at',
      businessClosed: 'The business does not operate on that day',
      businessOpensAt: 'The business opens at',
      reservationAfterClose: 'The reservation would end after closing time',
      timeConflict: 'That time slot is already booked for the selected resource',
      repeatLabel: 'Repeat',
      repeatDaysLabel: 'Days of the week',
      sessionCountLabel: 'Number of sessions',
      repeatHint: '{count} sessions will be created on the selected days, starting from the chosen date.',
      repeatDaysRequired: 'Select at least one day to repeat',
      seriesAllConflicted: "Couldn't create any session: every chosen time slot was already booked.",
      seriesPartialTitle: 'Created {created} of {total} sessions',
      seriesPartialDesc: "These dates couldn't be created because the time slot was already booked:",
      understood: 'Got it',
      partOfSeries: 'This reservation is part of a recurring series',
      seriesRemaining: '{count} sessions remaining',
      cancelSeriesRemaining: 'Cancel remaining sessions',
    },

    onboarding: {
      title: 'Welcome to iPlannit',
      subtitle: 'Complete these steps to start receiving reservations',
      hide: 'Hide',
      progress: 'Progress',
      of: 'of',
      completed: 'completed',
      start: 'Get started',
      steps: {
        business: { title: 'Set up your business', desc: 'Add your business name and timezone' },
        services: { title: 'Create your services', desc: 'Define the services you offer and their prices' },
        clients: { title: 'Add clients', desc: 'Register your first clients' },
        reservations: { title: 'Create your first reservation', desc: 'Schedule your first appointment' },
      },
    },

    settings: {
      title: 'Settings',
      subtitle: 'Manage your profile, business, and preferences',
      profileTab: 'Profile',
      businessTab: 'Business',
      notificationsTab: 'Notifications',
      planTab: 'Plan',
      teamTab: 'Team',
      team: {
        featureName: 'Team',
        title: 'Team',
        desc: "Add people to run the business with you, with access based on their role. None of them can touch business settings.",
        emailLabel: 'Email',
        emailPlaceholder: 'email@example.com',
        addBtn: 'Add',
        empty: "You haven't added anyone to your team yet.",
        hint: "The person must already have an iPlanit account. Their access depends on your Premium plan staying active.",
        added: 'Added {name}.',
        errorNotFound: "That email doesn't have an iPlanit account yet. Ask them to sign up first.",
        errorNotPremium: 'You need the Premium plan to add people to your team.',
        errorIsOwner: 'That email is already the owner of this business.',
        errorGeneric: "Couldn't add that person. Please try again.",
        roleAdmin: 'Admin',
        roleSales: 'Sales',
        roleAdminDesc: 'Full operational access (reservations, clients, services, resources, reports) except business settings.',
        roleSalesDesc: 'Reservations and clients only. No access to Services, Resources, or Reports.',
      },
      profileTitle: 'User Profile',
      profileDesc: 'Update your personal information',
      changePhoto: 'Change photo',
      photoHint: 'JPG, PNG or GIF. Max 2MB.',
      photoUploading: 'Uploading...',
      photoInvalidType: 'The file must be an image',
      photoTooLarge: 'The image must be under 2MB',
      photoUploadError: "Couldn't upload the photo. Please try again.",
      fullName: 'Full name',
      emailLabel: 'Email address',
      emailHint: 'Email address cannot be changed',
      securityTitle: 'Security',
      changePassword: 'Change password',
      lastUpdated: 'Last updated 3 months ago',
      businessTitle: 'Business Information',
      businessDesc: 'Configure your company details',
      businessName: 'Business name',
      businessCountry: 'Business country',
      countryPE: 'Peru',
      countryUS: 'United States',
      rucLabel: 'RUC (optional)',
      einLabel: 'EIN (optional)',
      businessCurrency: 'Business currency',
      currencyPEN: 'Soles (S/)',
      currencyUSD: 'US Dollars (US$)',
      businessCurrencyHint: "The currency you charge clients in. It doesn't have to match the business country.",
      cancellationPolicyLabel: 'Cancellation policy (hours)',
      cancellationPolicyHint: "Client cancellations with less notice than this are flagged as late in the client's history. Nothing is charged automatically - you decide whether to apply a penalty outside the system.",
      offersParkingLabel: 'Offer parking',
      offersParkingDesc: 'Turns on the Parking section to manage spots and offer the option when booking, internally and on your public page.',
      timezone: 'Timezone',
      address: 'Address',
      addressPlaceholder: 'Your business address',
      phone: 'Phone',
      phonePlaceholder: '+1 234 567 8900',
      contactEmail: 'Contact email',
      contactEmailPlaceholder: 'contact@yourbusiness.com',
      slugLabel: 'Custom link',
      slugRequired: "The link can't be empty.",
      slugTaken: 'Another business is already using that link, try a different one.',
      bookingLinkTitle: 'Booking link',
      bookingLinkDesc: "Share it with your clients so they can book on their own, without you having to enter every appointment yourself.",
      copyLink: 'Copy',
      linkCopied: 'Copied',
      bookingLinkUnavailable: 'Set your business name to generate your booking link.',
      hoursTitle: 'Business Hours',
      hoursDesc: 'Define the hours your business is available',
      closed: 'Closed',
      to: 'to',
      comingSoon: 'Coming soon',
      notifComingSoonBanner: "We don't send automatic emails yet - these settings are a preview of what's coming. Nothing here sends notifications for now.",
      notifTitle: 'Email Notifications',
      notifDesc: 'Configure which notifications you want to receive',
      confirmations: 'Reservation confirmations',
      confirmationsDesc: 'Receive email when a new reservation is created',
      reminders: 'Reminders',
      remindersDesc: 'Send reminders to clients before their appointment',
      reminderTiming: 'Reminder timing',
      cancellations: 'Cancellations',
      cancellationsDesc: 'Receive email when a reservation is cancelled',
      planTitle: 'Current Plan',
      freePlanDesc: 'You are on the free plan',
      premiumPlanDesc: 'You are on the premium plan',
      freePlanName: 'Free Plan',
      premiumPlanName: 'Premium Plan',
      freeFeatures: 'Basic limited features',
      premiumFeatures: '$20/month - Full access to all features',
      activeStatus: 'Active',
      upgradePremium: 'Upgrade to Premium',
      premiumFeaturesTitle: 'Premium Features',
      createBusinessTitle: 'Create Business',
      createBusinessDesc: "You don't have a business configured yet. Create one to get started.",
      createBusinessBtn: 'Create business',
      reminderH1: '1 hour before',
      reminderH2: '2 hours before',
      reminderH24: '24 hours before',
      reminderH48: '48 hours before',
      days: {
        monday: 'Monday',
        tuesday: 'Tuesday',
        wednesday: 'Wednesday',
        thursday: 'Thursday',
        friday: 'Friday',
        saturday: 'Saturday',
        sunday: 'Sunday',
      },
      premiumFeaturesList: [
        'Advanced analytics and reports',
        'Complete client history',
        'Demand and peak hour graphs',
        'Financial reports',
        'Data export',
        'Priority support',
      ],
    },

    mobileNav: {
      openMenu: 'Open menu',
      menuTitle: 'Navigation menu',
      menu: 'Menu',
      setupBusiness: 'Set up business',
      setupBusinessCta: 'Tap to get started',
      premium: 'Premium Plan',
      signOut: 'Sign out',
      defaultUser: 'User',
    },

    publicBooking: {
      notFoundTitle: 'Business not found',
      notFoundDesc: "Check the link, it might not be available anymore.",
      stepService: 'Choose a service',
      stepServiceDesc: 'Select what you want to book',
      stepDuration: 'Choose a duration',
      stepDurationDesc: 'This service has different durations available',
      stepHours: 'Choose how many hours',
      stepHoursDesc: 'The price is calculated automatically based on the hours you pick',
      flexibleDurationTag: 'Flexible duration',
      hourlyTag: 'Hourly',
      perHourShort: '/hour',
      hoursLabel: 'How many hours',
      hoursRangeHint: 'Between {min} and {max} hours.',
      totalPriceLabel: 'Total',
      fromPrice: 'From',
      noDurationOptions: 'This service has no durations configured yet',
      stepResource: 'Choose an option',
      stepResourceDesc: 'This service has more than one option available',
      stepDatetime: 'Choose date and time',
      stepDatetimeDesc: 'These are the available time slots',
      stepContact: 'Your details',
      stepContactDesc: 'To confirm your booking',
      noServices: 'This business has no services available yet.',
      back: 'Back',
      noSlots: 'No time slots available this day. Try another date.',
      continueBtn: 'Continue',
      nameLabel: 'Full name',
      emailLabel: 'Email (optional)',
      phoneLabel: 'Phone (optional)',
      notesLabel: 'Notes (optional)',
      contactHint: 'Leave at least an email or phone so they can reach you.',
      confirmBtn: 'Confirm booking',
      pendingHint: 'The business will review and confirm your request soon.',
      poweredBy: 'Booking powered by iPlanit',
      successTitle: 'Request sent',
      successDesc: "The business will confirm your booking soon.",
      errorTimeConflict: 'That time slot is no longer available. Please choose another.',
      errorNameRequired: 'Please enter your name.',
      errorContactRequired: 'Leave an email or phone number to reach you.',
      errorGeneric: "Couldn't complete the booking. Please try again.",
      needsParkingLabel: "Driving? Reserve a parking spot",
      errorParkingUnavailable: 'No parking spots are available at that time. You can continue without parking or pick another time.',
      parkingConfirmed: 'You have a parking spot reserved.',
      manageParkingConfirmed: 'You have parking confirmed for this reservation.',
      manageLinkTitle: 'Manage your reservation',
      manageLinkDesc: "Save this link: it's the only way to cancel your reservation without calling us.",
      manageNotFoundTitle: 'Reservation not found',
      manageNotFoundDesc: "Check the link, it might not exist anymore.",
      manageStatusLabel: 'Status',
      manageDatetimeLabel: 'Date and time',
      manageCancelBtn: 'Cancel my reservation',
      manageCancelling: 'Cancelling...',
      manageCancelConfirmTitle: 'Confirm cancellation',
      manageCancelConfirmDesc: 'This action cannot be undone.',
      manageCancelWindowWarning: "You're cancelling with less than {hours} hours notice. Under {business}'s policy, this may result in a penalty.",
      manageAlreadyCancelled: 'This reservation was already cancelled.',
      manageAlreadyCompleted: 'This reservation already took place.',
      manageAlreadyNoShow: 'This reservation was marked as a no-show.',
      manageCancelSuccess: 'Your reservation was cancelled.',
      manageCancelError: "Couldn't cancel your reservation. Please try again or contact the business.",
      manageKeepBtn: 'No, keep my reservation',
    },

    parking: {
      title: 'Parking',
      subtitle: 'Manage the parking spots you offer your clients',
      newSpot: 'New spot',
      setupRequired: 'Set up your business first',
      notEnabledTitle: 'Parking is not enabled',
      notEnabledDesc: 'Turn on "Offer parking" in Settings > Business to manage spots.',
      occupancyTitle: 'Occupancy right now',
      occupancyDesc: 'Spots currently occupied out of the active total',
      occupiedNow: 'Occupied now',
      noSpots: "You haven't added any parking spots yet",
      editSpotTitle: 'Edit spot',
      newSpotTitle: 'New parking spot',
      spotFormDesc: 'Each spot is an independent parking unit a client can reserve.',
      spotNameLabel: 'Name',
      spotNamePlaceholder: 'E.g. Spot 1',
      createSpotBtn: 'Create spot',
      deleteSpotTitle: 'Delete spot',
      deleteSpotDesc: 'This action cannot be undone.',
    },

    auth: {
      languageToggle: { es: 'ES', en: 'EN' },
      register: {
        title: 'Create account',
        stepPersonal: 'Enter your personal details',
        stepBusiness: 'Set up your business',
        fullName: 'Full name',
        fullNamePlaceholder: 'Your name',
        email: 'Email',
        emailPlaceholder: 'you@email.com',
        password: 'Password',
        passwordPlaceholderMin: 'At least 8 characters',
        continueBtn: 'Continue',
        businessName: 'Your business name',
        businessNamePlaceholder: 'E.g. Salud Plus Clinic',
        businessType: 'Business type',
        businessTypePlaceholder: 'Select a type',
        businessCountry: 'Business country',
        businessCountryPlaceholder: 'Select a country',
        countryPE: 'Peru',
        countryUS: 'United States',
        timezone: 'Timezone',
        timezonePlaceholder: 'Select your timezone',
        back: 'Back',
        createBtn: 'Create account',
        creating: 'Creating...',
        skipBusiness: "Skip, I'll join an existing business",
        haveAccount: 'Already have an account?',
        signIn: 'Sign in',
        fillAllFields: 'Please fill in all fields',
        passwordRequirements: 'Password must meet the requirements listed below',
        successTitle: 'Account created successfully!',
        successDesc: "Check your email to confirm your account. We'll take you to the sign-in page...",
        passwordStrength: { weak: 'Weak', medium: 'Medium', strong: 'Strong' },
        passwordReq: {
          length: 'At least 8 characters',
          uppercase: 'One uppercase letter',
          lowercase: 'One lowercase letter',
          number: 'One number',
          special: 'One symbol (optional)',
        },
        businessTypes: {
          coworking: 'Coworking / Workspaces',
          clinic: 'Clinic / Medical office',
          dental: 'Dental clinic',
          veterinary: 'Veterinary clinic',
          spa: 'Spa / Beauty center',
          salon: 'Hair salon / Barbershop',
          gym: 'Gym / Fitness studio',
          restaurant: 'Restaurant (table reservations)',
          education: 'Academy / Private lessons',
          photography: 'Photography studio',
          events: 'Event venue',
          consulting: 'Consulting / Professional advisory',
          professional: 'Independent professional',
          other: 'Other',
        },
      },
      login: {
        title: 'Sign in',
        subtitlePassword: 'Enter your credentials to access your account',
        subtitleMagic: "We'll send you a link to sign in without a password",
        email: 'Email',
        emailPlaceholder: 'you@email.com',
        password: 'Password',
        passwordPlaceholder: '********',
        signInBtn: 'Sign in',
        signingIn: 'Signing in...',
        sendMagicBtn: 'Send sign-in link',
        sendingMagic: 'Sending link...',
        useMagicLink: 'Or use a passwordless link',
        usePassword: 'Or use a password',
        noAccount: "Don't have an account?",
        signUp: 'Sign up',
        magicLinkSent: 'Sign-in link sent to your email! Check your inbox.',
        registeredWelcome: 'Account created successfully! Check your email to confirm it, then sign in.',
        forgotPassword: 'Forgot your password?',
      },
      forgotPassword: {
        title: 'Reset password',
        subtitle: "Enter your email and we'll send you a link to reset it",
        email: 'Email',
        emailPlaceholder: 'you@email.com',
        sendBtn: 'Send link',
        sending: 'Sending...',
        successTitle: 'Check your email',
        successDesc: "If an account exists for that email, we've sent a link to reset your password.",
        backToLogin: 'Back to sign in',
      },
      resetPassword: {
        title: 'New password',
        subtitle: 'Choose a new password for your account',
        newPassword: 'New password',
        confirmPassword: 'Confirm password',
        passwordPlaceholderMin: 'At least 8 characters',
        updateBtn: 'Update password',
        updating: 'Updating...',
        passwordsDontMatch: "Passwords don't match",
        passwordRequirements: 'Password must meet the requirements listed below',
        successTitle: 'Password updated!',
        successDesc: "We'll take you to your dashboard...",
        invalidLinkTitle: 'Invalid or expired link',
        invalidLinkDesc: 'Please request a new password reset link.',
        requestNewLink: 'Request new link',
        timeoutTitle: 'This is taking longer than usual',
        timeoutDesc: 'Your password may have already been updated. You\'re already signed in from this link, so you can go straight to your dashboard. If you can\'t sign in later with the new password, use "Forgot password" again.',
        goToDashboard: 'Go to my dashboard',
      },
    },

    analytics: {
      title: 'Analytics',
      subtitle: 'Understand the demand and performance of your business',
      rangeLabel: 'Period',
      range7d: 'Last 7 days',
      range30d: 'Last 30 days',
      range90d: 'Last 90 days',
      kpiReservations: 'Reservations',
      kpiRevenue: 'Estimated revenue',
      kpiOccupancy: 'Occupancy',
      kpiTopService: 'Most popular service',
      kpiNoShowRate: 'No-show rate',
      kpiVisits: 'Visits',
      kpiVisitsDesc: 'People who came to see the place',
      noData: 'Not enough data for this period',
      demandTitle: 'Demand by day',
      demandDesc: 'Reservations per day in the selected period',
      peakHoursTitle: 'Peak hours',
      peakHoursDesc: 'Which hours of the day your reservations cluster around',
      topServicesTitle: 'Most used services',
      topServicesDesc: 'Reservations by service in the selected period',
      revenueByServiceTitle: 'Revenue by service',
      revenueByServiceDesc: 'Estimated profitability by service',
      premiumTitle: 'Analytics is a Premium feature',
      premiumDesc: 'Unlock demand reports, peak hours, and your most profitable services',
      reservationsUnit: 'reservations',
      hoursBookedOf: 'of',
      hoursUnit: 'hours booked',
      accessRestricted: "You don't have access to this section",
      accessRestrictedDesc: 'Your role (Sales) does not include Reports.',
    },
  },
}

export type Translations = typeof TRANSLATIONS['es']

type LanguageContextType = {
  language: Language
  setLanguage: (lang: Language) => void
  locale: string
  t: Translations
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  // English by default until the visitor picks Spanish (or a saved
  // account/browser preference below overrides this on mount).
  const [language, setLanguageState] = useState<Language>('en')
  const { user, profile } = useAuthContext()
  // Tracks which profile.id we've already pulled a language from, so that an
  // unrelated profile refresh (e.g. after saving your name) doesn't clobber
  // a language you just picked manually in this session.
  const syncedProfileId = useRef<string | null>(null)

  // Pre-auth / fast-paint default: whatever this browser last used.
  useEffect(() => {
    const saved = localStorage.getItem('app-language') as Language | null
    if (saved === 'es' || saved === 'en') {
      setLanguageState(saved)
    }
  }, [])

  // Once logged in, the account's saved language (set at signup or in
  // Settings) is the source of truth - it should follow the user across
  // devices/browsers, not just live in this browser's localStorage.
  useEffect(() => {
    if (!profile) {
      syncedProfileId.current = null
      return
    }
    if (profile.id === syncedProfileId.current) return
    syncedProfileId.current = profile.id
    if (profile.language === 'es' || profile.language === 'en') {
      setLanguageState(profile.language)
      localStorage.setItem('app-language', profile.language)
    }
  }, [profile])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('app-language', lang)
    if (user) {
      supabase
        .from('profiles')
        .update({ language: lang })
        .eq('id', user.id)
        .then(({ error }) => {
          if (error) console.error('[v0] Error saving language preference:', error)
        })
    }
  }

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage,
      locale: TRANSLATIONS[language].locale,
      t: TRANSLATIONS[language],
    }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}
